status: wip
collated: true
context:
  __title: Term Collapsed
  open: false
  textBefore: <p>Om interpretatieproblemen te voorkomen heeft het
  term: W3C
  content: World Wide Web Consortium
  textAfter: aanbevelingen opgesteld over welke tags geldig zijn en hoe ze moeten worden geïnterpreteerd. De oorspronkelijke aanbeveling is een aantal malen geactualiseerd in verband met verdere ontwikkeling van HTML.</p>
variants:
  - name: expanded
    context:
      __title: Term Expanded
      open: true
