status: ready
collated: true
default: alert
variants:
  - name: alert
    context:
      icon: di di-warning
  - name: info
    notes: Een font kan worden vergroot met modifier classes `.di-2x` tot `.di-6x`.
    context:
      icon: di di-info di-2x
  - name: ok
    context:
      icon: di di-vink di-4x
  - name: cross
    context:
      icon: di di-cross di-6x
