notes: |
status: ready
context:
  menu:
    modifier: main
    items:
      - label: Home
      - label: Vergunningcheck
      - label: Aanvragen
        active: true
      - label: Regels op de kaart
      - label: Mijn Omgevingsloket
  steps:
    title: 7. Verzoeken indienen
    step: Stap 7 van 7
  alert:
    modifier: info
    sronly: "Opmerking:"
    message: |
      We hebben van uw aanvraag meerdere verzoeken gemaakt. Hier ziet u waar u de verzoeken indient.
  accordion:
    sections:
    - title: Veehouderij
      id: panel1
      open: true
      sections:
      - title: Beschrijving installatie en activiteiten
        id: panel1
        open: true
        fieldsets:
          - groups:
              - id: documenten
                inputType: files
                description: Geef een tekening van de nieuwe situatie in 1:100. Een situatietekening geeft een schets van de bestaande en de nieuwe situatie met daarop duidelijk de maatvoering en de schaalaanduiding (1:100).
                files:
                  - filename: Schetsen_en_foto’s_1.pdf
                  - filename: Bijlagen_hoveniersbedrijf_de_heggeschaar_hoveniers.jpg
                    confidential: true
        buttons:
        - type: button
          modifier: primary
          label: Volgende
    - title: Beschrijving grondstoffen en hulpstoffen
      id: panel2
    - title: Energiegebruik en maatregelen
      id: panel3
    - title: Emissies, maatregelen en technieken
      id: panel4
    - title: Beschrijving toestand van de lokatie
      id: panel5
    - title: Afvalstoffen
      id: panel6
