notes: |
order: 4
status: ready
context:
  menu:
    modifier: main
    items:
      - label: Home
      - label: Vergunningcheck
      - label: Aanvragen
        active: true
      - label: Regels op de kaart
      - label: Mijn Omgevingsloket
  steps:
    title: 7. Verzoeken indienen
    step: Stap 7 van 7
  accordion:
    sections:
    - title: "Verzoek 1: Object Laan van Eik en Duinen 125, 's-Gravenhage 1"
      id: panel1
    - title: "Verzoek 2: Object Laan van Eik en Duinen 125, 's-Gravenhage 2"
      id: panel2
      open: true
      definitions:
      - term: "Indienen bij:"
        descriptions:
          - description: Gemeente Den Haag
      - term: "Soort:"
        descriptions:
          - description: Melding
      - term: "Bevat:"
        descriptions:
          - description: Milieubelastende activiteit - Vergunning (Gemeente)
      - term: "Omgevingsoverleg mogelijk:"
        descriptions:
          - description: Ja
      fieldsets:
        - groups:
          - id: toelichting
            inputType: textarea
            rows: 5
            label: Ruimte om uw verzoek toe te lichten
  form:
    fieldsets:
    - modifier: form-vertical
      groups:
      - id: confirm
        inputType: confirm
        label: Hierbij verklaar ik alle vragen naar waarheid te hebben ingevuld.
    asideButtons:
    - type: button
      modifier: link
      label: Vorige 
      icon: chevron-left
    buttons:
    - type: button
      modifier: default
      label: Downloaden
    - type: submit
      modifier: primary
      label: Indienen
