status: wip
variants:
  - name: default
    context:
      cards:
        - label: Omgevingsplan Nieuwegein
          content: Gemeente Nieuwegein lorem ipsum dolor sit amet, consectetur adipiscing elit.
  - name: aside
    context:
      interactionsOri: aside
      cards:
        - label: Omgevingsplan Nieuwegein
          content: Gemeente Nieuwegein lorem ipsum dolor sit amet, consectetur adipiscing elit.
          toggle:
            - id: 1
              value: 0
          info: true
        - label: Brouwersmolen
          content: Brouwersmolen eget iaculis nisi quam in libero.
          toggle:
            - id: 1
              value: 0
          info: true
  - name: below
    context:
      interactionsOri: below
      cards:
        - label: Omgevingsplan Nieuwegein
          content: Gemeente Nieuwegein lorem ipsum dolor sit amet, consectetur adipiscing elit.
          toggle:
            - id: 1
              value: 0
          info: true
        - label: Brouwersmolen
          content: Brouwersmolen eget iaculis nisi quam in libero.
          toggle:
            - id: 1
              value: 0
          info: true
