status: wip
collated: true
variants:
  - name: default
    context:
      cards:
        - label: Omgevingsplan Nieuwegein
          content: Gemeente Nieuwegein lorem ipsum dolor sit amet, consectetur adipiscing elit.
  - name: aside
    context:
      interactionsOri: aside
      cards:
        - label: Omgevingsplan Nieuwegein
          content: Gemeente Nieuwegein lorem ipsum dolor sit amet, consectetur adipiscing elit.
          toggle:
            - id: omgevingsplan-nieuwegein
              value: 0
          infoExplanation: bij Omgevingsplan Nieuwegein
        - label: Brouwersmolen
          content: Brouwersmolen eget iaculis nisi quam in libero.
          toggle:
            - id: brouwersmolen
              value: 0
          infoExplanation: bij Brouwersmolen
  - name: below
    context:
      interactionsOri: below
      cards:
        - label: Omgevingsplan Nieuwegein
          content: Gemeente Nieuwegein lorem ipsum dolor sit amet, consectetur adipiscing elit.
          toggle:
            - id: omgevingsplan-nieuwegein
              value: 0
          infoExplanation: bij Omgevingsplan Nieuwegein
        - label: Brouwersmolen
          content: Brouwersmolen eget iaculis nisi quam in libero.
          toggle:
            - id: brouwersmolen
              value: 0
          infoExplanation: bij Brouwersmolen
