notes:
  Een knopje achter het formlabel. Dit is te bereiken door `.dso-info` op `.form-group` te zetten.
  En een `button` achter de label-tekst. De class `.dso-info-open` doet de toelichting tonen.
id: toggle-info-open
collated: true
context:
  infoTitle: Toelichting titel
  infoText: |
    <h4>Heading 4</h4>
    <p>Lorem ipsum dolor sit amet, <strong>consectetur</strong> adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
    Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
    Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.</p>
  infoLink: Lees meer
  infoLinkIcon: fas fa-chevron-down
variants:
- name: toggle-info-open-more
  context:
    __title: Uitgeklapte tekst
    __explanation:
    - De tekst is verder uitgeklapt en de uitklap-link is een inklap-link geworden.
    infoTitle: Toelichting titel
    infoText: |
      <h4>Heading 4</h4>
      <p>Lorem ipsum dolor sit amet, <strong>consectetur</strong> adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
      Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
      Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.</p>

      <p>Lorem ipsum dolor sit amet, <strong>consectetur</strong> adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
      Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
      Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.</p>
    infoLink: Lees minder
    infoLinkIcon: fas fa-chevron-up
