notes: |
  Toont een dropdown met daarin een gevulde uitklapper. Gebaseerd op de Bootstrap "Dropdowns" component
status: ready
collated: true
default: dropdown
context:
  id: actie
  open: false
  label: Actie
variants:
  - name: dropdown-open
    context:
      id: actie_open
      open: true
      items:
        -
          - label: Actie
          - label: Andere actie
  - name: dropdown-open
    context:
      id: actie_open
      open: true
      align: right
      items:
        -
          - label: Actie
          - label: Andere actie
          - label: Nog iets anders hier
        -
          - label: Gescheiden link
  - name: dropdown-open
    context:
      id: actie_open
      open: true
      selectable: true
      items:
        -
          - label: Actie geselecteerd
            selected: true
          - label: Andere actie
          - label: Nog iets anders hier
        -
          - label: Gescheiden link
