notes: |
  Toont een dropdown met daarin een gevulde uitklapper. Gebaseerd op de Bootstrap "Dropdowns" component
status: ready
collated: true
default: dropdown
context:
  id: actie
  open: false
  label: Actie
variants:
  - name: dropdown-open
    context:
      id: actie_open
      open: true
      items:
        -
          - Actie
          - Andere actie
          - Nog iets anders hier
        -
          - Gescheiden link
