notes: |
  Een list-button met class 'selected' heeft een svg met de class 'check', een list-button met de class 'multiple-selected' heeft een span met de class 'selected'.
status: wip
collated: true
context:
  type: button
  label: Milieubelastende activiteit - Melding
variants:
  - name: button selected
    context:
      count: 1
  - name: button multiple selected
    context:
      count: 99
  - name: button disabled
    context:
      disabled: true
