notes: |

status: wip
context:
  type: button
  label: Milieubelastende activiteit - Melding
variants:
  - name: button selected
    context:
      modifier: selected
      icon: true
  - name: button multiple selected
    context:
      modifier: multiple-selected
      counter: '99x'
  - name: button disabled
    context:
      modifier: disabled
      disabled: true
