notes: |
  Een list-button met class 'selected' heeft een svg met de class 'check', een list-button met de class 'multiple-selected' heeft een span met de class 'selected'.
status: wip
context:
  type: button
  label: Milieubelastende activiteit - Melding
variants:
  - name: button selected
    context:
      modifier: selected
      icon: true
  - name: button multiple selected
    context:
      modifier: multiple-selected
      counter: '99x'
  - name: button disabled
    context:
      modifier: disabled
      disabled: true
