notes: |

status: wip
context:
  type: button
  label: Milieubelastende activiteit - Melding
variants:
  - name: button selected
    modifier: selected
    context:
      icon: true
  - name: button multiple selected
    modifier: multiple-selected
    context:
      counter: '99x'
  - name: button disabled
    context:
      disabled: true
      modifier: disabled
