status: wip
collated: true
context:
  __title: Collapsed
  description-hidden: true
  text-before: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  term: Html
  content: |
    HyperText Markup Language is een op SGML gebaseerde opmaaktaal voor de specificatie van documenten, voornamelijk bedoeld voor het wereldwijde web. Het is de standaard opmaaktaal voor webpagina's. Documenten in HTML kunnen geopend en gelezen worden door een webbrowser om vervolgens als webpagina weergegeven te worden.
  text-after: |
      neque massa, feugiat sed, commodo in, adipiscing ut, est. In fermentum mattis ligula. Nulla ipsum. Vestibulum condimentum condimentum augue. Nunc purus risus, volutpat sagittis, lobortis at, dignissim sed, sapien. Fusce porttitor iaculis ante. Curabitur eu arcu. Morbi quam purus, tempor eget, ullamcorper feugiat, commodo ullamcorper, neque.
variants:
  - name: button
    context:
      __title: Expanded
      description-hidden: false
