status: wip
collated: true
context:
  __title: Collapsed
  description-hidden: true
  text-before: Om interpretatieproblemen te voorkomen heeft het
  term: W3C
  content: World Wide Web Consortium
  text-after: aanbevelingen opgesteld over welke tags geldig zijn en hoe ze moeten worden geïnterpreteerd. De oorspronkelijke aanbeveling is een aantal malen geactualiseerd in verband met verdere ontwikkeling van HTML.
variants:
  - name: expanded
    context:
      __title: Expanded
      description-hidden: false
