notes: |
  Het content element (`.dso-description-content`) moet direct na het term element (`.dso-description-term`) gebruikt worden. Het tonen/verbergen van de content kan met een `.dso-open` modifier op `.dso-description-term`, maar het content element mag ook scriptend volledig achterwege worden gelaten.

  Als scriptend het content element achterwege wordt gelaten, moet bij het tonen van de content nog steeds `.dso-open` op het term element geplaatst worden, en het content element moet nog steeds direct na het term element worden geplaatst.
status: wip
collated: true
context:
  __title: Collapsed
  open: false
  text-before: Om interpretatieproblemen te voorkomen heeft het
  term: W3C
  content: World Wide Web Consortium
  text-after: aanbevelingen opgesteld over welke tags geldig zijn en hoe ze moeten worden geïnterpreteerd. De oorspronkelijke aanbeveling is een aantal malen geactualiseerd in verband met verdere ontwikkeling van HTML.
variants:
  - name: expanded
    context:
      __title: Expanded
      open: true
