notes: |
  Voeg een kop toe met `.panel-heading`. Je kunt daarbinnen elke `<h1>`-`<h6>` met een `.panel-title` class plaatsen om een pre-styled heading te krijgen. Let op, de font-sizes van de `<h1>`-`<h6>` wordt overschreven door de `.panel-heading`.

  Voeg een footer toe met '.panel-footer`. Let op, de panel footer erft geen kleuren en randen wanneer 'contextual variations' worden gebruikt.
status: ready
collated: true
context:
  title: Standaard panel
  body: Panel content
  modifier: default
variants:
  - name: footer
    context:
      title: H1 Panel title
      header: h1
      footer: Panel footer
  - name: primary
    context:
      title: Panel contextual primary
      footer: Panel footer
      modifier: primary
  - name: success
    context:
      title: Panel contextual success
      footer: Panel footer
      modifier: success
  - name: info
    context:
      title: Panel contextual info
      footer: Panel footer
      modifier: info
  - name: warning
    context:
      title: Panel contextual warning
      footer: Panel footer
      modifier: warning
  - name: danger
    context:
      title: Panel contextual danger
      footer: Panel footer
      modifier: danger
