notes: |
  Toont een sitepad (breadcrumbs).
status: ready
context:
  __title: breadcrumbs
  crumbs:
  - label: Home
    url: '#'
  - label: Zelf aan de slag
    url: '#'
  - label: Inhoud
    url: '#'
