meta:
  webComponent: dso-alert
  markup: true
notes: |
  Alerts geven contextuele feedback op acties van de gebruiker of tonen belangrijke informatie vanuit het systeem. Ze trekken de aandacht van de gebruiker zonder de taak van de gebruiker te onderbreken. Het is aan te raden om alerts bovenaan de gerelateerde sectie te laten zien. Zorg dat feedback als gevolg van een gebruikersactie altijd in beeld verschijnt.

  Gebruikers kunnen alerts niet afwijzen. Alerts verdwijnen pas als de situatie is opgelost of de gebruiker een nieuwe actie uitvoert.

  ## Technische opmerkingen
  Gebaseerd op het Bootstrap **Alerts** component. Plaats de inhoud van `.alert` liefst in een `.dso-rich-content`. Plaats buttons in een `<p>` als ze nodig zijn. Zie component pagina.

  ## Wanneer te gebruiken
  Gebruik een alert om feedback te geven op acties van de gebruiker of om belangrijke systeeminformatie te laten zien. Ze worden ook samen gebruikt met inline validatie in lange formulieren.

  Type meldingen:
  - **Foutmelding:** Foutmeldingen laten de gebruiker weten dat er iets is misgegaan nadat ze hebben geprobeerd iets te doen.
  - **Waarschuwing:** Waarschuwingen laten gebruikers weten dat ze acties ondernemen die niet wenselijk zijn of onverwachte resultaten kunnen hebben.
  - **Bevestiging:** Succesmeldingen laten de gebruiker weten dat ze een actie of taak hebben voltooid.
  - **Toelichting:** Toelichtingen geven aanvullende informatie die niet altijd is gekoppeld aan de huidige actie of taak.

  ## Wanneer niet te gebruiken
  Gebruik geen alert om invoervelden te valideren bij lange formulieren. Gebruik dan altijd in-line validatie op veldniveau. Zet het eventueel naast een alert met het overzicht van foutmeldingen bovenaan het formulier.

  Gebruik ook geen alert voor destructieve acties. Zo kunt u  bij een verwijderactie beter een blokkerend patroon gebruiken, zoals een modal. Zo kan de gebruiker bevestigen dat dit is wat hij wil.

  ## Hoe te gebruiken
  - Houd meldingen zo kort mogelijk.
  - Wees beschrijvend en geef gebruikers duidelijke vervolgstappen.
  - Bedek andere inhoud niet met een alert.
  - De breedte van een alert varieert op basis van de context en pagina-indeling.
  - Plaats alerts bovenaan de gerelateerde sectie.
  - Zorg dat een alert altijd in beeld verschijnt.
  - Probeer dezelfde type meldingen te combineren.
  - Meerdere alerts worden verticaal gestapeld, met de nieuwste bovenaan de lijst.

  ## Gedrag en toegankelijkheid
  Een alert met ARIA `role="alert"` wordt onmiddellijk aangekondigd als het wordt toegevoegd aan de DOM . Een screenreader plaatst hier automatisch het woord 'melding' voor.

  Gebruik `role="alert"` alleen als de melding verschijnt als gevolg van een actie door de gebruiker.

  Vraag jezelf altijd af wanneer de flow van de gebruiker moet worden onderbroken. Bijvoorbeeld als een toelichting of waarschuwingsalert vast op de pagina staat als die wordt geladen, is het niet nodig een `role="alert"` toe te kennen. In veel gevallen geldt: wees terughoudend met het gebruik van meldingen.

  **Meerdere alerts**
  Het kan voorkomen dat er een alert op de pagina staat en er door een gebruikersactie nóg een alert bijkomt. Zorg er dan altijd voor dat de nieuwste alert een `role="alert"` krijgt en de overige alerts niet. Er mag dus slechts één alert een `role="alert"` bevatten.

  ## Bronvermelding
  - Nielsen Norman Group (1994, 24 april). 10 Usability Heuristics for User Interface Design. Geraadpleegd op 20 juli 2020, via https://www.nngroup.com/articles/ten-usability-heuristics/
  - Nielsen Norman Group (2015, 26 juli). Indicators, Validations, and Notifications. Geraadpleegd op 2 oktober 2020, via https://www.nngroup.com/articles/indicators-validations-notifications/
  - Web Content Accessibility Guidelines (2018, 05 June). WC3. Geraadpleegd op 20 juli 2020, via https://www.w3.org/WAI/standards-guidelines/wcag/
  - Accessibility Developer Guide (2018, 15 mei 15). Noticing screen readers using alert role. Geraadpleegd op 16 oktober 2020, via https://www.accessibility-developer-guide.com/examples/sensible-aria-usage/alert/
status: ready
collated: true
context:
  __title: success
  status: success
  message: Dit is een succesmelding. Deze wordt getoond als een proces succesvol is afgerond.
variants:
  - name: with-role-alert
    context:
      __title: met role alert
      status: success
      message: Dit is een succesmelding. Deze wordt getoond als een proces succesvol is afgerond.
      roleAlert: true
  - name: danger
    context:
      __title: danger
      status: danger
      message: Dit is een <a href="#">foutmelding</a>. Deze wordt getoond als er iets is misgegaan.
  - name: warning
    context:
      __title: warning
      status: warning
      message: Dit is een waarschuwingsmelding. Deze wordt gebruikt voor waarschuwingen.
  - name: info
    context:
      __title: info
      status: info
      message: Dit is een informatiemelding. Deze wordt gebruikt voor <a href="#">aanvullende</a> informatie of tips.
  - name: success-button
    context:
      __title: success with button
      status: success
      message: |
        <div class="dso-rich-content">
          <p>Dit is een succesmelding. Deze wordt getoond als een proces succesvol is afgerond.</p>
          <button type="button" class="btn">Button</button>
        </div>
  - name: danger-button
    context:
      __title: danger with button
      status: danger
      message: |
        <div class="dso-rich-content">
          <p>Dit is een foutmelding. Deze wordt getoond als er iets is misgegaan.</p>
          <button type="button" class="btn">Button</button>
        </div>
  - name: warning-button
    context:
      __title: warning with button
      status: warning
      message: |
        <div class="dso-rich-content">
          <p>Dit is een waarschuwingsmelding. Deze wordt gebruikt voor waarschuwingen.</p>
          <button type="button" class="btn">Zoekopdracht afbreken</button>
        </div>
  - name: info-button
    context:
      __title: info with button
      status: info
      message: |
        <div class="dso-rich-content">
          <p>Dit is een informatiemelding. Deze wordt gebruikt voor aanvullende informatie of tips.</p>
          <button type="button" class="btn">Button</button>
        </div>
  - name: alert with headings
    context:
      __title: alert with headings
      status: info
      message: |
        <div class="dso-rich-content">
          <h2>Dit is een H2</h2>
          <p>Dit is een informatiemelding. Deze wordt gebruikt voor aanvullende informatie of tips.</p>
          <h3>Dit is een H3</h3>
          <p>Dit is een informatiemelding. Deze wordt gebruikt voor aanvullende informatie of tips.</p>
          <h4>Dit is een H4</h4>
          <p>Dit is een informatiemelding. Deze wordt gebruikt voor aanvullende informatie of tips.</p>
          <h5>Dit is een H5</h5>
          <p>Dit is een informatiemelding. Deze wordt gebruikt voor aanvullende informatie of tips.</p>
          <h6>Dit is een H6</h6>
          <p>Dit is een informatiemelding. Deze wordt gebruikt voor aanvullende informatie of tips.</p>
        </div>
