meta:
  webComponent: dso-alert
  markup: false
status: ready
collated: true
context:
  __title: success
  status: success
  message: Dit is een succesmelding. Deze wordt getoond als een proces succesvol is afgerond.
variants:
  - name: with-role-alert
    context:
      __title: met role alert
      status: success
      message: Dit is een succesmelding. Deze wordt getoond als een proces succesvol is afgerond.
      roleAlert: true
  - name: error
    context:
      __title: error
      status: error
      message: Dit is een <a href="#">foutmelding</a>. Deze wordt getoond als er iets is misgegaan.
  - name: warning
    context:
      __title: warning
      status: warning
      message: Dit is een waarschuwingsmelding. Deze wordt gebruikt voor waarschuwingen.
  - name: info
    context:
      __title: info
      status: info
      message: Dit is een informatiemelding. Deze wordt gebruikt voor <a href="#" class="extern" target="_blank" rel="noopener noreferrer">aanvullende</a> informatie of tips.
  - name: success-button
    context:
      __title: success with button
      status: success
      message: |
        <div class="dso-rich-content">
          <p>Dit is een succesmelding. Deze wordt getoond als een proces succesvol is afgerond.</p>
          <button type="button" class="btn">Button</button>
        </div>
  - name: danger-button
    context:
      __title: danger with button
      status: danger
      message: |
        <div class="dso-rich-content">
          <p>Dit is een foutmelding. Deze wordt getoond als er iets is misgegaan.</p>
          <button type="button" class="btn">Button</button>
        </div>
  - name: warning-button
    context:
      __title: warning with button
      status: warning
      message: |
        <div class="dso-rich-content">
          <p>Dit is een waarschuwingsmelding. Deze wordt gebruikt voor waarschuwingen.</p>
          <button type="button" class="btn">Zoekopdracht afbreken</button>
        </div>
  - name: info-button
    context:
      __title: info with button
      status: info
      message: |
        <div class="dso-rich-content">
          <p>Dit is een informatiemelding. Deze wordt gebruikt voor aanvullende informatie of tips.</p>
          <button type="button" class="btn">Button</button>
        </div>
  - name: alert with headings
    context:
      __title: alert with headings
      status: info
      message: |
        <div class="dso-rich-content">
          <h2>Dit is een H2</h2>
          <p>Dit is een informatiemelding. Deze wordt gebruikt voor aanvullende informatie of tips.</p>
          <h3>Dit is een H3</h3>
          <p>Dit is een informatiemelding. Deze wordt gebruikt voor aanvullende informatie of tips.</p>
          <h4>Dit is een H4</h4>
          <p>Dit is een informatiemelding. Deze wordt gebruikt voor aanvullende informatie of tips.</p>
          <h5>Dit is een H5</h5>
          <p>Dit is een informatiemelding. Deze wordt gebruikt voor aanvullende informatie of tips.</p>
          <h6>Dit is een H6</h6>
          <p>Dit is een informatiemelding. Deze wordt gebruikt voor aanvullende informatie of tips.</p>
        </div>
