status: ready
collated: true
context:
  count: 5
  current: 3
variants:
  - name: 1-1
    context:
      __title: 1 pagina
      count: 1
      current: 1
  - name: 2-1
    context:
      __title: 2 pagina's
      __explanation: pagina 1 geselecteerd
      count: 2
      current: 1
  - name: 2-2
    context:
      __title: 2 pagina's
      __explanation: pagina 2 geselecteerd
      count: 2
      current: 2
  - name: 3-1
    context:
      __title: 3 pagina's
      __explanation: pagina 1 geselecteerd
      count: 3
      current: 1
  - name: 3-2
    context:
      __title: 3 pagina's
      __explanation: pagina 2 geselecteerd
      count: 3
      current: 2
  - name: 3-3
    context:
      __title: 3 pagina's
      __explanation: pagina 3 geselecteerd
      count: 3
      current: 3
  - name: 4-1
    context:
      __title: 4 pagina's
      __explanation: pagina 1 geselecteerd
      count: 4
      current: 1
  - name: 4-2
    context:
      __title: 4 pagina's
      __explanation: pagina 2 geselecteerd
      count: 4
      current: 2
  - name: 4-3
    context:
      __title: 4 pagina's
      __explanation: pagina 3 geselecteerd
      count: 4
      current: 3
  - name: 4-4
    context:
      __title: 4 pagina's
      __explanation: pagina 4 geselecteerd
      count: 4
      current: 4
  - name: 5-1
    context:
      __title: 5 pagina's
      __explanation: pagina 1 geselecteerd
      count: 5
      current: 1
  - name: 5-2
    context:
      __title: 5 pagina's
      __explanation: pagina 2 geselecteerd
      count: 5
      current: 2
  - name: 5-3
    context:
      __title: 5 pagina's
      __explanation: pagina 3 geselecteerd
      count: 5
      current: 3
  - name: 5-4
    context:
      __title: 5 pagina's
      __explanation: pagina 4 geselecteerd
      count: 5
      current: 4
  - name: 5-5
    context:
      __title: 5 pagina's
      __explanation: pagina 5 geselecteerd
      count: 5
      current: 5
