notes: |
  * 100% Bootstrap compatible markup
  * Als het niet mogelijk is om vanaf de huidige pagina naar een vorige of volgende pagina te gaan, dan toont deze knop niet
status: ready
label: Pagination
collated: true
context:
  count: 5
  current: 3
variants:
  - name: 1-1
    context:
      count: 1
      current: 1
  - name: 2-1
    context:
      count: 2
      current: 1
  - name: 2-2
    context:
      count: 2
      current: 2
  - name: 3-1
    context:
      count: 3
      current: 1
  - name: 3-2
    context:
      count: 3
      current: 2
  - name: 3-3
    context:
      count: 3
      current: 3
