status: wip
collated: true
context:
  count: 99
  current: 22
variants:
  - name: 1-1
    context:
      count: 1
      current: 1
  - name: 2-1
    context:
      count: 2
      current: 1
  - name: 2-2
    context:
      count: 2
      current: 2
  - name: 3-1
    context:
      count: 3
      current: 1
  - name: 3-2
    context:
      count: 3
      current: 2
  - name: 3-3
    context:
      count: 3
      current: 3
  - name: 4-1
    context:
      count: 4
      current: 1
  - name: 4-2
    context:
      count: 4
      current: 2
  - name: 4-3
    context:
      count: 4
      current: 3
  - name: 4-4
    context:
      count: 4
      current: 4
  - name: 5-1
    context:
      count: 5
      current: 1
  - name: 5-2
    context:
      count: 5
      current: 2
  - name: 5-3
    context:
      count: 5
      current: 3
  - name: 5-4
    context:
      count: 5
      current: 4
  - name: 5-5
    context:
      count: 5
      current: 5
  - name: 6-1
    context:
      count: 6
      current: 1
  - name: 6-2
    context:
      count: 6
      current: 2
  - name: 6-3
    context:
      count: 6
      current: 3
  - name: 6-4
    context:
      count: 6
      current: 4
  - name: 6-5
    context:
      count: 6
      current: 5
  - name: 6-6
    context:
      count: 6
      current: 6
  - name: 7-3
    context:
      count: 7
      current: 3
  - name: 7-4
    context:
      count: 7
      current: 4
  - name: 7-5
    context:
      count: 7
      current: 5
  - name: 100-100
    context:
      count: 100
      current: 100
  - name: 100-1
    context:
      count: 100
      current: 1
  - name: 500-50
    context:
      count: 500
      current: 50
