collated: true
context:
  __title: default
  shoppingcartTitle: Mijn activiteiten
  shoppingcartTitleTag: h2
  items: []
variants:
  - name: items-collapsed
    context:
      __title: items collapsed
      collapsed: true
      items:
        - label: Milieubelastende activiteit - Melding
        - label: Milieubelastende activiteit - Melding
          additive: 2
  - name: items-expanded
    context:
      __title: items expanded
      items:
        - label: Milieubelastende activiteit - Melding
        - label: Milieubelastende activiteit - Melding
          additive: 2
  - name: items-edit
    context:
      __title: edit items
      items:
        - label: Milieubelastende activiteit - Melding
        - label: Milieubelastende activiteit - Melding
          additive: 2
          edit: true
  - name: subitems
    context:
      __title: subitems
      items:
        - label: Milieubelastende activiteit - Melding
          subitems:
            - label: Wasstraat of wasplaats
        - label: Milieubelastende activiteit - Melding
          additive: Wasstraat om de hoek van garagebedrijf Jansen
          edit: true
          subitems:
            - label: Wasstraat of wasplaats
        - label: Milieubelastende activiteit gereguleerd in het omgevingsplan - Informatie (Rijk)
          readonly: true
          subitems:
            - label: Koelwater, niet afkomstig van een milieubelastende activiteit die is aangewezen in hoofdstuk 3 van het Besluit activiteiten, lozen in het riool of op of in de bodem.
  - name: subitems-hidden-summary
    context:
      __title: subitems with hidden summary
      hideSummary: true
      items:
        - label: Milieubelastende activiteit - Melding
          subitems:
            - label: Wasstraat of wasplaats
        - label: Milieubelastende activiteit - Melding
          additive: Wasstraat om de hoek van garagebedrijf Jansen
          edit: true
          subitems:
            - label: Wasstraat of wasplaats
  - name: subitems with warning
    context:
      __title: subitems with warning
      items:
        - label: Tankstation starten of veranderen
          readonly: true
          subitems:
            - label: Tanken van diesel, benzine en andere vloeibare brandstof
            - label: Tanken en opslaan van LPG
        - label: Opslaan van vloeistoffen in een opslagtank
          readonly: true
          subitems:
            - label: Opslaan van vloeistoffen in een ondergrondse opslagtank
              warning: true
