notes: |
  Een List group is een flexibele en krachtige component om simpele en complexe lijsten van elementen te tonen, met custom content.
  Gebaseerd op de Bootstrap "List group" component
status: ready
default: unordered-list
context:
  items:
    - text: Cras justo odio
    - text: Dapibus ac facilisis in
    - text: Morbi leo risus
    - text: Porta ac consectetur ac
    - paragraph: Vestibulum at eros
variants:
  - name: ordered-list
  - name: list-group
