status: wip
collated: true
context:
  id: beleg
  type: select
  label: Select
  multiple: true
  options:
    - optionType: Vlees
      items:
        - value: worst
          label: Worst
        - value: salami
          label: Salami
        - value: geit
          label: Geit
    - optionType: Vis
      items:
        - value: zalm
          label: Zalm
        - value: makreel
          label: Makreel
variants:
  - name: input-focus
    context:
      id: group_input_focus
      type: text
      label: Select - Focus
      inputModifiers: " example-focus"
      multiple: true
      options:
        - optionType: Vlees
          items:
            - value: worst
              label: Worst
            - value: salami
              label: Salami
            - value: geit
              label: Geit
        - optionType: Vis
          items:
            - value: zalm
              label: Zalm
            - value: makreel
              label: Makreel
  - name: input-feedback
    context:
      id: group_input_feedback
      type: text
      label: Select - Feedback
      inputModifiers: " example-default"
      helpText: Deze producten worden allemaal gemaakt in een fabriek waar ook noten worden verwerkt
      multiple: true
      options:
        - optionType: Vlees
          items:
            - value: worst
              label: Worst
            - value: salami
              label: Salami
            - value: geit
              label: Geit
        - optionType: Vis
          items:
            - value: zalm
              label: Zalm
            - value: makreel
              label: Makreel
  - name: input-required
    context:
      id: group_input_required
      type: text
      label: Select - Verplicht
      required: true
      multiple: true
      options:
        - optionType: Vlees
          items:
            - value: worst
              label: Worst
            - value: salami
              label: Salami
            - value: geit
              label: Geit
        - optionType: Vis
          items:
            - value: zalm
              label: Zalm
            - value: makreel
              label: Makreel
  - name: input-ongeldig
    context:
      id: group_input_invalid
      type: text
      label: Select - Ongeldig
      inputModifiers: " invalid"
      required: true
      errorText: Maak een geldige selectie
      multiple: true
      options:
        - optionType: Vlees
          items:
            - value: worst
              label: Worst
            - value: salami
              label: Salami
            - value: geit
              label: Geit
        - optionType: Vis
          items:
            - value: zalm
              label: Zalm
            - value: makreel
              label: Makreel
  - name: input-ongeldig-feedback
    context:
      id: group_input_invalid-feedback
      type: text
      label: Select - Ongeldig / Feedback
      inputModifiers: " invalid"
      required: true
      errorText: Maak een geldige selectie
      helpText: Deze producten worden allemaal gemaakt in een fabriek waar ook noten worden verwerkt
      multiple: true
      options:
        - optionType: Vlees
          items:
            - value: worst
              label: Worst
            - value: salami
              label: Salami
            - value: geit
              label: Geit
        - optionType: Vis
          items:
            - value: zalm
              label: Zalm
            - value: makreel
              label: Makreel
  - name: input-uitleg
    context:
      id: group_input_explanation
      type: text
      label: Select - Uitleg
      inputModifiers: " example-default"
      helpIcon: true
      multiple: true
      options:
        - optionType: Vlees
          items:
            - value: worst
              label: Worst
            - value: salami
              label: Salami
            - value: geit
              label: Geit
        - optionType: Vis
          items:
            - value: zalm
              label: Zalm
            - value: makreel
              label: Makreel
