status: wip
collated: true
context:
  id: input-select
  label: Kies uw beleg
  options:
  - optionType: Vlees
    items:
    - value: worst
      label: Worst
    - value: salami
      label: Salami
    - value: geit
      label: Geit
  - optionType: Vis
    items:
    - value: zalm
      label: Zalm
    - value: makreel
      label: Makreel
variants:
- name: input-select-multiple
  context:
    __title: Multiple
    __explanation:
    - Indien een multiple select gewenst is, dient er een <code>.dso-multiple</code>
      class gezet te worden op de div met de class <code>.dso-select</code>.
    id: input-select-multiple
    multiple: true
    helpText: Maak een keuze tussen vlees of vis
- name: input-select-invalid
  context:
    __title: Ongeldig
    __explanation:
    - Indien een select ongeldig is, dient er een <code>.dso-invalid</code> class
      gezet te worden op de div met de class <code>.dso-select</code>.
    id: input-select-invalid
    required: true
    helpText: Maak een keuze tussen vlees of vis
    state: invalid
    errorText: Dit veld is verplicht
- name: input-select-valid
  context:
    __title: Geldig
    __explanation:
    - Indien een select ongeldig was en valide wordt gemaakt, dient de
      <code>.dso-invalid</code> class vervangen te worden door de class <code>.dso-valid</code>.
    id: input-select-valid
    required: true
    state: valid
    helpText: Maak een keuze tussen vlees of vis
- name: input-select-disabled
  context:
    __title: Disabled
    id: input-select-disabled
    required: true
    disabled: true
