context:
  search:
    id: input-text-icon
    label: Zoeken
    inputIcon: search
  menu:
    modifier: main
    items:
      - label: Documentatie
        active: true
      - label: Component
      - label: HTML
      - label: Context
      - label: Assets
  navs:
    - items:
      - label: documentatie
      - label: Introductie
        items:
          - label: Voor ontwerpers
          - label: Voor ontwikkelaars
          - label: Toegankelijkheid
      - label: Versies
        items:
          - label: Alle versies
    - items:
      - label: fundament
      - label: Grid
      - label: Kleuren
      - label: Logo / favicon
      - label: Typografie
