context:
  search:
    id: input-text-icon
    label: Zoeken
    inputIcon: search
  menu:
    modifier: main
    items:
      - label: Documentatie
        active: true
      - label: Component
      - label: HTML
      - label: Context
      - label: Assets
  navs:
    - items:
      - label: documentatie
      - label: Introductie
        items:
          - label: Voor ontwerpers
          - label: Voor ontwikkelaars
          - label: Toegankelijkheid
      - label: Versies
        items:
          - label: Alle versies
    - items:
      - label: fundament
      - label: Grid
      - label: Kleuren
      - label: Logo / favicon
      - label: Typografie
  content: |
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi consectetur augue augue, a dapibus augue luctus sit amet. Nullam nec lorem fermentum, hendrerit erat a, convallis purus. Donec posuere malesuada enim, sit amet consequat enim malesuada in. Nullam sit amet velit orci. Sed bibendum sem sed neque aliquam, sit amet pretium tortor cursus. Vestibulum ac dignissim nunc. Duis vel erat euismod, molestie metus ut, posuere justo. Integer tincidunt libero ipsum, imperdiet porttitor orci laoreet a. Phasellus sollicitudin ipsum in massa fermentum, at porttitor urna auctor. Vestibulum ultrices arcu ac volutpat porttitor. Suspendisse in semper augue. Sed nibh mauris, pulvinar ut elementum ac, hendrerit iaculis nisi. Phasellus varius lectus eu euismod placerat. Quisque id ipsum ipsum.</p>
      <p>Praesent a tellus congue arcu facilisis rhoncus vitae at purus. Nam placerat neque sed velit gravida ultrices. Sed tempus mauris velit, vitae semper erat tempor vitae. Etiam a hendrerit urna, auctor porttitor mauris. Donec euismod, ipsum in tincidunt laoreet, mauris quam pellentesque ante, in dictum tortor nibh in tellus. Donec id consequat libero. Mauris hendrerit tempus hendrerit. Nulla facilisi. Duis finibus luctus rutrum. Aliquam magna arcu, convallis quis elit sollicitudin, eleifend semper massa. Proin nec sem turpis. Curabitur ultrices felis non risus tristique, ut venenatis diam eleifend. Vivamus erat purus, mattis in dui eu, varius malesuada orci. Phasellus consectetur ligula massa, eu placerat neque venenatis sed. Duis vitae nibh lectus.</p>
      <p>Integer viverra arcu sed porttitor accumsan. Nunc vel porttitor purus. Praesent at gravida odio. Quisque sodales nisi sed ligula efficitur, in commodo orci mattis. Ut a augue erat. Vivamus quis tincidunt turpis. Nunc quis libero pretium, suscipit dolor nec, vestibulum mauris. Nam laoreet ante iaculis, tempor purus eget, auctor ligula. Aenean vestibulum porttitor urna, et pretium nulla sodales id. Fusce feugiat neque non lorem iaculis fringilla. Phasellus ut feugiat neque. Sed blandit elit quis urna dictum, a elementum enim elementum. Suspendisse sodales sapien eget diam consequat aliquet.</p>
      <p>Aliquam erat volutpat. Curabitur vel vulputate sapien. Etiam at varius quam. Suspendisse viverra, ipsum eget blandit auctor, ante velit condimentum justo, at fermentum ex est at dolor. Fusce eget suscipit felis, vel ultricies orci. Curabitur molestie convallis ultricies. Etiam sed ipsum eget neque imperdiet faucibus. Maecenas fringilla, eros ut commodo laoreet, urna quam feugiat neque, in bibendum libero arcu vel velit. Nam semper, nunc sed aliquam consectetur, turpis eros tincidunt neque, quis rutrum sem urna nec mi. Nulla euismod tortor id velit posuere ultrices. Pellentesque egestas sem faucibus egestas iaculis. Sed gravida nisl eu metus elementum lobortis. Cras scelerisque egestas rutrum. Donec nec gravida lectus. Pellentesque accumsan eget lacus quis cursus. Integer vel erat porttitor, malesuada augue et, sagittis lorem.</p>
