status: wip
collated: true
context:
  id: group_input_voorbeeld
  type: text
  label: Text veld
variants:
  - name: input-focus
    context:
      id: group_input_focus
      type: text
      label: Text veld - Focus
      inputModifiers: " example-focus"
  - name: input-feedback
    context:
      id: group_input_feedback
      type: text
      label: Text veld - Feedback
      inputModifiers: " example-default"
      helpText: Minimaal 6 tekens waarvan 1 leesteken
  - name: input-verplicht
    context:
      id: group_input_required
      type: text
      label: Text veld - Verplicht
      required: true
  - name: input-ongeldig
    context:
      id: group_input_invalid
      type: text
      label: Text veld - Ongeldig
      inputModifiers: " invalid"
      required: true
      errorText: Minimaal 6 tekens waarvan 1 leesteken
  - name: input-ongeldig-feedback
    context:
      id: group_input_invalid-feedback
      type: text
      label: Text veld - Ongeldig / Feedback
      inputModifiers: " invalid"
      required: true
      errorText: Voer een geldig e-mailadres in
      helpText: Minimaal 6 tekens waarvan 1 leesteken
  - name: input-icoon
    context:
      id: group_input_icon
      type: text
      label: Text veld - Icoon
      inputModifiers: " example-default"
      inputIcon: fas fa-calendar
  - name: input-uitleg
    context:
      id: group_input_explanation
      type: text
      label: Text veld - Uitleg
      inputModifiers: " example-default"
      helpIcon: true
