notes: |
  Een formulier begint altijd met een `form` element. Elke _textuele_ `input` **en** `select` zit in een `.form-group`. Elk formulier onderdeel is een _groep_ met een `label`.

  Alle elementen zitten in een `fieldset` met een `legend`. De legend kan verborgen worden met een `.sr-only`. De form submit (en eventueel een form reset) staat _buiten_ de fieldset.

  * Een eventuele toelichting zit in een `p.help-block`. Als er een toelichting is, dient deze met een `@aria-describedby` aan de input gekoppeld te worden.
  * Een label bij een _textuele_ `input` **of** `select` eindigd altijd met een dubbelepunt.

  #### Extra:
  * https://getbootstrap.com/docs/3.3/css/#forms
  * [H91: Using HTML form controls and links](https://www.w3.org/TR/WCAG20-TECHS/H91)
status: ready
label: Voorbeeld
context:
  fieldsets:
    - legend: Contact
      groups:
        - id: voornaam
          type: input
          inputType: text
          label: Voornaam
          required: true
        - id: achternaam
          type: input
          inputType: text
          label: Achternaam
          helpText: Mag ook de familienaam zijn
        - type: static
          label: Geslacht
          value: Man
        - id: geboortedatum
          type: input
          inputType: text
          label: Geboortedatum
          hasFeedback: true
          feedbackIcon: fa fa-calendar-o
          optional: true
        - id: email
          type: input
          inputType: email
          label: E-mailadres
          required: true
        - id: password
          type: input
          inputType: password
          label: Wachtwoord
        - id: password_bevestig
          type: input
          inputType: password
          label: Wachtwoord (bevestig)
        - id: nieuwsbrief
          type: confirm
          label: Stuur mij de maandelijkse nieuwsbrief
          helpText: Uw gegevens zullen niet worden gedeeld met derden
    - legend: Beleg
      groups:
        - id: beleg
          type: select
          label: Beleg
          multiple: true
          optional: true
          options:
            - optionType: Vlees
              items:
                - value: worst
                  label: Worst
                - value: salami
                  label: Salami
                - value: geit
                  label: Geit
            - optionType: Vis
              items:
                - value: zalm
                  label: Zalm
                - value: makreel
                  label: Makreel
    - legend: Auto merk
      groups:
        - id: auto_merk
          type: select
          label: Type auto
          optional: true
          options:
            - optionType: Europees
              items:
                - value: alfa
                  label: Alfa Romeo
                - value: fiat
                  label: Fiat
                - value: marcedes
                  label: Mercedes
                  selected: true
                - value: volkswagen
                  label: Volkswagen
    - legend: Aanhanger
      groups:
        - id: aanhanger
          type: radios
          label: Welke aanhanger
          optional: true
          options:
            - value: bak
              label: Bak
            - value: caravan
              label: Caravan
              checked: true
            - value: fietsendrager
              label: Fietsendrager
            - value: oplegger
              label: Oplegger
    - legend: Vraag
      groups:
        - id: gekke_vraag
          type: textarea
          rows: 5
          label: Waarom heeft een tankstation dat 24 uur per dag open is een slot op de deur?
          helpText: Deze vraag heeft een toelichting
  submitButton:
    type: submit
    modifier: primary
    label: Verstuur
