export const imroContent = `<p
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:imropt="http://www.geonovum.nl/imro/pt/2012/1.0"
  xmlns:xl="http://www.w3.org/1999/xlink"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
  <strong>Beleidskeuze:</strong>
</p>
<p
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:imropt="http://www.geonovum.nl/imro/pt/2012/1.0"
  xmlns:xl="http://www.w3.org/1999/xlink"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
  De provincie realiseert, samen met de MRDH, een adequaat aanbod van Openbaar Vervoer in het vervoergebied van de provincie Zuid-Holland. Openbaar vervoer moet snel, betrouwbaar en beschikbaar zijn en is daarmee een volwaardig alternatief.<br /><br />Goed openbaar vervoer (OV) voldoet aan de kwaliteitscriteria snel, frequent, betrouwbaar, beschikbaar en betaalbaar. Samen met lopen, de fiets en deelsystemen maakt OV een reis van deur tot deur mogelijk. We zetten in op verbeteringen waar OV sterk is: snelle collectieve verplaatsingen tussen kernen.
</p>
<p
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:imropt="http://www.geonovum.nl/imro/pt/2012/1.0"
  xmlns:xl="http://www.w3.org/1999/xlink"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
  <strong>Aanleiding:</strong>
</p>
<p
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:imropt="http://www.geonovum.nl/imro/pt/2012/1.0"
  xmlns:xl="http://www.w3.org/1999/xlink"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
  Door economische groei worden naar verwachting niet alleen meer reizen gemaakt door bestaande inwoners, maar er komen tot 2040 ook nog 240.000 huizen bij. We zien een verschuiving, waarbij mensen in steden minder van de auto gebruik maken en juist vaker kiezen voor actieve vervoerswijzen als lopen, fietsen en openbaar vervoer. Reispatronen van mensen worden steeds gevarieerder. Hierbij combineren reizigers steeds meer bestemmingen op een reis. Dit stelt extra eisen aan het mobiliteitssysteem, het voor- en natransport en de ruimtelijke ordening.
</p>
<p
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:imropt="http://www.geonovum.nl/imro/pt/2012/1.0"
  xmlns:xl="http://www.w3.org/1999/xlink"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
  <strong>Motivering Provinciaal Belang:</strong>
</p>
<p
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:imropt="http://www.geonovum.nl/imro/pt/2012/1.0"
  xmlns:xl="http://www.w3.org/1999/xlink"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
  Op grond van de Wet Personenvervoer 2000 is de provincie Zuid-Holland opdrachtgever voor het openbaar vervoer in de regio’s Holland Rijnland, Midden-Holland, Drechtsteden en Alblasserwaard, en de gemeenten Hoeksche Waard en Goeree Overflakkee.
</p>
<p
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:imropt="http://www.geonovum.nl/imro/pt/2012/1.0"
  xmlns:xl="http://www.w3.org/1999/xlink"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
  <strong>Toelichting:</strong>
</p>
<p
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:imropt="http://www.geonovum.nl/imro/pt/2012/1.0"
  xmlns:xl="http://www.w3.org/1999/xlink"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>
  Het bestaande mobiliteitssysteem is onvoldoende toegerust om de groei in personenmobiliteit te verwerken en zorgt regelmatig voor files en parkeerproblemen. Daarom gaan we mensen positief verleiden van modaliteiten gebruik te maken die de groei op een duurzame manier kunnen opvangen. Ook stimuleren we verschuiving van reizen van de spits- naar de daluren, zodat het systeem zo optimaal mogelijk wordt benut.<br /><br />Mensen moeten zoveel mogelijk keuzevrijheid hebben om de modaliteiten te kiezen die het best bij hun reis passen. De reis van deur-tot-deur staat hierbij centraal. Iedereen moet zich kunnen verplaatsen. Hiervoor wordt het mobiliteitsnetwerk compleet gemaakt en wordt overstappen tussen modaliteiten zo makkelijk mogelijk.<br /><br />Per locatie is maatwerk nodig om te kijken welke mix van modaliteiten het best passend is. We zetten in op het vergroten van het aandeel gezonde, duurzame en ruimtelijk efficiënte modaliteiten als lopen, fietsen en openbaar vervoer. Dit doen we door deze modaliteiten zo aantrekkelijk te maken dat het een logisch alternatief wordt voor de reiziger. Dit kan door het bestaande systeem te verbeteren door te investeren in nieuw hoogwaardig OV en snelfietsroutes, door te bouwen bij bestaand hoogwaardig OV en de openbare ruimte anders in te richten. We zetten in op betere ketenmobiliteit door overstappen tussen modaliteiten makkelijker te maken. We stimuleren – daar waar het kan – lopen, fietsen vervolgens OV-gebruik en pas daarna privaat autogebruik.
</p>
<p
  xmlns="http://www.w3.org/1999/xhtml"
  xmlns:imropt="http://www.geonovum.nl/imro/pt/2012/1.0"
  xmlns:xl="http://www.w3.org/1999/xlink"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
></p>
`;
