notes: |
status: ready
context:
  steps:
    title: 2. Locatie
    step: Stap 1/7
  filter:
    placeholder: Zoek een adres
    icon: true
    label: Adres
  buttons:
  - type: default
    modifier: default
    label: Vorige stap
    icon: chevron-left
  - type: submit
    modifier: primary
    label: Volgende stap
    iconAfter: chevron-right
  