notes: |
  Een help block staat altijd direct in de `.form-group`.

  Als de checkbox een disabled state heeft, dan moet er een `.disabled` op de `.radio` worden geplaatst. Zonder deze modifier zal er geen "niet toegestaan" cursor op het `label` zijn
status: ready
context:
  id: checkbox_voorbeeld
  label: Getal
  helpText: Kies een even getal
  options:
    - value: 1
      label: een
    - value: 2
      label: twee
    - value: 3
      label: drie
