status: ready
collated: true
context:
  __title: default
  source: /dummy/images/sneeuwpop.png
  alt: Afbeelding van een sneeuwpop
variants:
  - name: Responsive
    context:
      __title: responsive
      modifier: img-responsive
  - name: Rounded
    context:
      __title: rounded
      modifier: img-rounded
  - name: Circle
    context:
      __title: circle
      modifier: img-circle
  - name: Thumbnail
    context:
      __title: thumbnail
      modifier: img-thumbnail
