label: Progress Indicator (CSS Component)
status: ready
collated: true
context:
  __title: Spinner small (24px)
  labelid: progress-indicator-label
  label: "Resultaten laden: een moment geduld alstublieft."
  size: small
variants:
- name: spinner-medium-infinite
  context:
    __title: Spinner medium (32px)
    labelid: progress-indicator-label-md
    size: medium
- name: spinner-large-infinite
  context:
    __title: Spinner large (48px)
    labelid: progress-indicator-label-sm
    size: large
- name: spinner-small-block
  context:
    __title: Spinner small - gecentreerd blok
    labelid: progress-indicator-label-sm-block
    size: small
    block: true
- name: spinner-large-block
  context:
    __title: Spinner large - gecentreerd blok
    labelid: progress-indicator-label-lg-block
    size: large
    block: true
