status: ready
collated: true
context:
  __title: Standaard
  tabs:
    - label: Zoek op adres
      url: '#'
      modifiers: active
    - label: Postcode en huisnummer
      url: '#'
    - label: Kadastraal nummer
      url: '#'
    - label: Coordinaten
      url: '#'
variants:
  - name: tab disabled
    context:
      __title: Tab deactief
      tabs:
        - label: Zoek op adres
          url: '#'
        - label: Postcode en huisnummer
          url: '#'
          modifiers: active
        - label: Kadastraal nummer
          url: '#'
        - label: Coordinaten
          url: '#'
          modifiers: disabled
