notes: |
  <pIn een tabel kan ook gefilterd worden op basis van gebruikersinvoer doormiddel van een zoekveld boven de tabel. Er wordt direct automatisch gefilterd in de tabel.</p>

status: ready
context:
  modifier: table
  caption: Overzicht bronnen
  icon: true
  placeholder: Tabel doorzoeken
  button: hidden
  small: true
  columnHeaders:
    - title: Nummer
    - title: Bron
    - title: Uitleg 
  rowContent:
    - rowHeader: 1
      bron: AQUO
      uitleg: In de Aquo-begrippenset staan begrippen, die worden gebruikt in de watersector.   
    - rowHeader: 2
      bron: BesluitActiviteitenLeefomgeving
      uitleg: Besluit Activiteiten Leefomgeving
    - rowHeader: 3
      bron: BesluitBouwwerkenLeefomgeving
      uitleg: Besluit Bouwwerken Leefomgeving
variants:
  - name: no results
    context:
      modifier: table
      caption: Overzicht bronnen
      icon: true
      placeholder: 123456
      button: hidden
      small: true
      columnHeaders:
        - title: Nummer
        - title: Bron
        - title: Uitleg 
      resultError: Geen resultaten gevonden
      cols: 3

