meta:
  webComponent: dso-date-picker
collated: true
context:
  label: Default
  id: initial
variants:
  - name: disabled
    context:
      label: Disabled
      id: disabled
      disabled: true
  - name: showButton
    context:
      label: Toon kalender knop
      id: showButton
      showButton: true
  - name: predefined-value
    context:
      label: Vooringevulde datum
      id: predefinedValue
      value: 15-11-2020
  - name: min-max
    context:
      label: Minimum en maximum datum
      id: min-max
      min: 8-1-2020
      max: 29-1-2020
