context:
  __title: Subtitel voor een heading
  content: |
    <h2>Stelselcatalogus Omgevingswet</h2>
    <p>De Stelselcatalogus Omgevingswet (DSO StelselCatalogus) is een online naslagwerk en dient als ondersteunend binnen de DSO-LV. In de DSO StelselCatalogus kunt u begrippen, activiteiten, werkzaamheden, waardelijsten en informatieproducten vinden die bruikbaar zijn binnen de DSO Keten en afkomstig uit diverse domeinen.</p>
variants:
- name: subtitel-before-text
  context:
    __title: Subtitel voor een paragraaf
    content: |
      <p>De Stelselcatalogus Omgevingswet (DSO StelselCatalogus) is een online naslagwerk en dient als ondersteunend binnen de DSO-LV. In de DSO StelselCatalogus kunt u begrippen, activiteiten, werkzaamheden, waardelijsten en informatieproducten vinden die bruikbaar zijn binnen de DSO Keten en afkomstig uit diverse domeinen.</p>
- name: subtitel-before-definition-list
  context:
    __title: Subtitel voor een Definitie Lijst
    definitionList:
      modifier: dso-bordered
      definitions:
        - term: "Thema:"
          descriptions:
            - description: Wonen
            - description: Werken
        - term: "Regelkwalificatie:"
          descriptions:
            - description: Instructieregels
