/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DsoAlert {
        "level": 'success' | 'info' | 'warning' | 'danger';
    }
    interface DsoBadge {
        "level"?: 'primary' | 'success' | 'info' | 'warning' | 'danger';
        "status"?: string;
    }
}
declare global {
    interface HTMLDsoAlertElement extends Components.DsoAlert, HTMLStencilElement {
    }
    var HTMLDsoAlertElement: {
        prototype: HTMLDsoAlertElement;
        new (): HTMLDsoAlertElement;
    };
    interface HTMLDsoBadgeElement extends Components.DsoBadge, HTMLStencilElement {
    }
    var HTMLDsoBadgeElement: {
        prototype: HTMLDsoBadgeElement;
        new (): HTMLDsoBadgeElement;
    };
    interface HTMLElementTagNameMap {
        "dso-alert": HTMLDsoAlertElement;
        "dso-badge": HTMLDsoBadgeElement;
    }
}
declare namespace LocalJSX {
    interface DsoAlert {
        "level"?: 'success' | 'info' | 'warning' | 'danger';
    }
    interface DsoBadge {
        "level"?: 'primary' | 'success' | 'info' | 'warning' | 'danger';
        "status"?: string;
    }
    interface IntrinsicElements {
        "dso-alert": DsoAlert;
        "dso-badge": DsoBadge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dso-alert": LocalJSX.DsoAlert & JSXBase.HTMLAttributes<HTMLDsoAlertElement>;
            "dso-badge": LocalJSX.DsoBadge & JSXBase.HTMLAttributes<HTMLDsoBadgeElement>;
        }
    }
}
