notes: |
  Een table met accordion-fcuhntioonaliteit met (`.dso-accordion-talbe`) bestaat uit secties (`.dso-accordion-section`). Een sectie heeft een handle (`.dso-section-handle`) en body (`.dso-section-body`).

  Een accordion section (`tr`) in de state "open" moet een `.dso-open` class op `.dso-accordion-section` krijgen. Dit zorgt voor oranje tekst en het "chevron-up"-icoon. Ook als het
  `.dso-accordion-section` element niet in het DOM staat, moet een open accordion altijd `.dso-open` krijgen.

  De class `dso-no-top-border` zorgt er voor dat de eerste `.dso-accordion-section` geen `border-top` krijgt.

status: wip
context:
  modifiers: dso-no-top-border
  head:
  - tablehead: Aanvraag/melding
  sections:
  - title: Vergunning kappen
    id: panel1
  - title: Boom 23 kappen
    id: panel2
  - title: Pand 24 slopen
    id: panel3
    open: true
  - title: Kerkstraat 10 tuin uitgraven
    id: panel4
  - title: Grote Markt 31 kabels leggen
    id: panel5
