notes: |
status: ready
context:
  modifier: table
  caption: Overzicht toegevoegde documenten
  columnHeaders:
    # - title: "#"
    - title: Documentnaam 
    - title: Eigenaar 
    - title: Upload datum
  rowContent:
    # - rowHeader: 1
    - linkHref: tekening
      documentNaam: Tekening.jpg
      eigenaar: P.J. Puk
      uploadDatum: 21-07-2019
    # rowNotification: success
    # - rowHeader: 2
    - linkHref: omgevingsplan
      documentNaam: Omgevingsplan.pdf
      eigenaar: H.G. Griff
      uploadDatum: 22-07-2019
    # - rowHeader: 3
    - linkHref: bodemonderzoek
      documentNaam: Bodemonderzoek.pdf
      eigenaar: P.J. Puk
      uploadDatum: 23-07-2019
    # - rowHeader: 4
    - linkHref: maatregelen
      documentNaam: Maatregelen.pdf
      eigenaar: P.J. Puk
      uploadDatum: 23-07-2019
    # - rowHeader: 5
    - linkHref: omgevingsplan
      documentNaam: Plattegrond.pdf
      eigenaar: P.J. Puk
      uploadDatum: 28-07-2019