notes: |
  <p>In het voorbeeld hieronder is de data is oplopend gesorteerd voor de kolom "Bron". Dit wordt aangeduid met <code>role=columnheader"</code> en <code>aria-sort="ascending"</code>. Daarnaast is de data niet aanpasbaar in dit voorbeeld. Zodoende wordt ook <code>aria-readonly="true"</code> gebruikt.</p>

status: ready
context:
  modifier: table
  caption: Overzicht bronnen
  columnHeaders:
    - title: Nummer
      sorteerbaar: ascending
    - title: Bron
      sorteerbaar: true
    - title: Uitleg 
      sorteerbaar: true
  rowContent:
    - rowHeader: 1
      bron: Omgevingsbesluit  
      uitleg: Omgevingsbesluit
    - rowHeader: 2
      bron: Omgevingswet
      uitleg: Omgevingswet
    - rowHeader: 3
      bron: VNGBegrippenkaderGemeenten
      uitleg: Dit is de bron waar alle VNG begrippen op gebaseerd zijn.
    - rowHeader: 4
      bron: BesluitActiviteitenLeefomgeving
      uitleg: Besluit Activiteiten Leefomgeving
    - rowHeader: 5
      bron: BesluitBouwwerkenLeefomgeving
      uitleg: Besluit Bouwwerken Leefomgeving
    - rowHeader: 6
      bron: BesluitKwaliteitLeefomgeving
      uitleg: Besluit Kwaliteit Leefomgeving
    - rowHeader: 7
      bron: AQUO
      uitleg: In de Aquo-begrippenset staan begrippen, die worden gebruikt in de watersector.   
variants:
  - name: descending
    modifier: table
    context:
      caption: Overzicht bronnen
      columnHeaders:
        - title: Nummer
          sorteerbaar: descending
        - title: Bron
          sorteerbaar: true
        - title: Uitleg 
          sorteerbaar: true
      rowContent:
        - rowHeader: 7
          bron: AQUO
          uitleg: In de Aquo-begrippenset staan begrippen, die worden gebruikt in de watersector.   
        - rowHeader: 6
          bron: BesluitKwaliteitLeefomgeving
          uitleg: Besluit Kwaliteit Leefomgeving
        - rowHeader: 5
          bron: BesluitBouwwerkenLeefomgeving
          uitleg: Besluit Bouwwerken Leefomgeving
        - rowHeader: 4
          bron: BesluitActiviteitenLeefomgeving
          uitleg: Besluit Activiteiten Leefomgeving
        - rowHeader: 3
          bron: VNGBegrippenkaderGemeenten
          uitleg: Dit is de bron waar alle VNG begrippen op gebaseerd zijn.
        - rowHeader: 2
          bron: Omgevingswet
          uitleg: Omgevingswet
        - rowHeader: 1
          bron: Omgevingsbesluit  
          uitleg: Omgevingsbesluit
