notes: |
  Toont een carousel met x-aantal slides. Gebaseerd op Bootstrap "Carousel.js"
status: ready
context:
  carouselId: MyCarousel
  slides:
    - active: true
      image: /dummy/images/stap-voor-stap.jpg
      imageAlt: Chania
    - image: /dummy/images/mensen-steken-hand-op.jpg
      imageAlt: Chania
    - image: /dummy/images/deze-bestaat-niet.jpg
      imageAlt: Oeps
