notes: |
  De aside met de checklist schuift mee met het formulier, tot hij een punt bereikt waar hij niet verder MAG scrollen.
  We gebruiken hiervoor Bootstrap Affix, en deze heeft twee values - `data-offset-top` en `data-offset-bottom` - die bepalen waar het kantelpunt zit.
  Let op de uitlijning die te zien is in onderstaande instructie afbeelding.

  Zie ook
  * [Bootstrap Affix](https://getbootstrap.com/docs/3.3/javascript/#affix)
  * Positioneren van de affix, links in het menu onder het kopje "Documentation"
status: ready
context:
  breadcrumbs:
    crumbs:
      - label: Home
        url: '#'
      - label: Aanvragen
        url: '#'
      - label: Mijn project
        url: '#'
      - label: Aanvraag voorbereiden
        url: '#'
  sections:
  - title: Veehouderij
    id: panel1
    state: warning
    open: true
    sections:
    - title: Beschrijving installatie en activiteiten
      id: panel1
      description: Geef een tekening van de nieuwe situatie in 1:100. Een situatietekening geeft een schets van de bestaande en de nieuwe situatie met daarop duidelijk de maatvoering en de schaalaanduiding (1:100).
      open: true
      files:
        - filename: Schetsen_en_foto’s_1.pdf
        - filename: Bijlagen_hoveniersbedrijf_de_heggeschaar_hoveniers.jpg
          confidential: true
  - title: Beschrijving grondstoffen en hulpstoffen
    id: panel2
  - title: Energiegebruik en maatregelen
    id: panel3
  - title: Emissies, maatregelen en technieken
    id: panel4
  - title: Beschrijving toestand van de lokatie
    id: panel5
  - title: Afvalstoffen
    id: panel6
