notes: |
status: wip
context:
  menu: 
    modifier: main
    items: 
      - label: Menu titel A
        active: true
      - label: Menu titel B
      - label: Menu titel C
  breadcrumbs:
    crumbs:
      - label: Home
        url: '#'
      - label: Menu titel A
        url: '#'
