notes: |
status: ready
context:
  menu:
    modifier: main
    items:
      - label: Home
      - label: Vergunningcheck
      - label: Aanvragen
        active: true
      - label: Regels op de kaart
      - label: Mijn Omgevingsloket
  title: Kies hier hoe u wilt inloggen
  breadcrumbs:
    crumbs:
      - label: Home
        url: '#'
      - label: Inloggen
        url: '#'
     
  