notes: |
  Standaard worden de knoppen gecentreerd. Wil je ze aan de zijkant uitlijnen, dan dien je `.previous` en `.next` te plaatsen op de `li's`.

  Een pager is navigatie. Om de Bootstrap documentatie te citeren:
  > #### Labelling the pagination component
  > The pagination component should be wrapped in a <nav> element to identify it as a navigation section to screen readers and other assistive technologies. In addition, as a page is likely to have more than one such navigation section already (such as the primary navigation in the header, or a sidebar navigation), it is advisable to provide a descriptive `aria-label` for the `<nav>` which reflects its purpose. For example, if the pagination component is used to navigate between a set of search results, an appropriate label could be `aria-label="Search results pages"`.

  (https://getbootstrap.com/docs/3.3/components/#callout-pagination-label)
status: ready
collated: true
context:
  __title: centered
variants:
  - name: centered_disabled
    context:
      __title: centered with button disabled
      firstPage: true
  - name: aligned
    template: aligned
    context:
      __title: aligned
      lastPage: true
