notes: |
order: 30
status: ready
context:
  appheading:
    title: Aanvraag Laan van Eik en Duinen 125, Den Haag
    subtitle: 2. Locatie
    step: Stap 2/7
  dropdownButton:
    modifier: dso-tertiary
    label: 'Meer zoekopties'
    items:
      - label: Adres
      - label: Postcode en huisnummer
      - label: Kadastraal nummer
      - label: Coordinaten
      - Label: Teken een gebied op de kaart
  typeSelect:
    id: type
    inputType: select
    label: Type
    options:
      - value: rd
        label: RD
      - value: wgs84
        label: WGS84
        selected: true
  inputLatt:
    value: 52.07066496
    icon: true
    label: Lattitude
    hideSearchButton: true
  inputLong:
    value: 4.26389251
    icon: true
    label: Longitude
