notes: |
  Een List group is een flexibele en krachtige component om simpele en complexe lijsten van elementen te tonen, met custom content.
  Gebaseerd op de Bootstrap "List group" component
status: ready
default: unordered-list
context:
  items:
    - label: Cras justo odio
    - label: Dapibus ac facilisis in
    - label: Morbi leo risus
    - label: Porta ac consectetur ac
    - label: Vestibulum at eros
variants:
  - name: ordered-list
  - name: list-group
