notes: |
  Een List group is een flexibele en krachtige component om simpele en complexe lijsten van elementen te tonen, met custom content.
  Gebaseerd op de Bootstrap "List group" component
status: ready
default: unordered-list
context:
  items:
    - Cras justo odio
    - Dapibus ac facilisis in
    - Morbi leo risus
    - Porta ac consectetur ac
    - Vestibulum at eros
variants:
  - name: ordered-list
  - name: list-group
