status: ready
context:
  cards:
    - label: Omgevingsplan Nieuwegein
      content: Gemeente Nieuwegein lorem ipsum dolor sit amet, consectetur adipiscing elit.
    - label: 'Brouwersmolen'
      content: 'Brouwersmolen eget iaculis nisi quam in libero.'
      interactions:
        - button:
            type: button
            modifier: dso-tertiary
            icon: info
            label: Toon informatie over Brouwersmolen
            iconOnly: true
    - label: 'Brouwersmolen'
      content: 'Brouwersmolen eget iaculis nisi quam in libero.'
      interactions:
        - button:
            type: button
            modifier: dso-tertiary
            icon: info
            label: Toon informatie over Brouwersmolen
            iconOnly: true
