status: wip
collated: true
context:
  __title: "Example: Open/Close"
  __explanation: Animatie demo. Animates moeten aangezet worden dmv. <code>.dso-searchbar.dso-animate</code>
  __switches:
    - name: state
      label: Open/sluit
  id: searchbar
  label: Zoeken
variants:
  - name: searchbar-closed
    context:
      __title: Zoekbalk gesloten
      __explanation: De zoekbalk dient vanuit zichzelf de class <code>.dso-searchbar</code> te hebben en kan worden geopend met de modifier classes <code>.dso-open</code>. Het toevoegen/verwijderen van deze modifier classes start een animatie die de zoekbalk opent of sluit.
      __switches: null
      id: searchbarClosed
  - name: searchbar-opened
    context:
      __title: Zoekbalk open
      __explanation: Om een zoekbalk te openen dient de class <code>.dso-open</code> toegevoegd te worden. Sluiten gaat door de class weer te verwijderen
      __switches: null
      id: searchbarOpened
      open: true
