collated: true
context:
  __title: default
  type: button
  label: Milieubelastende activiteit - Melding
variants:
  - name: button selected
    context:
      __title: button selected
      count: 1
  - name: button multiple selected
    context:
      __title: button multiple selected
      count: 99
  - name: button disabled
    context:
      __title: button disabled
      disabled: true
  - name: button met optionele tekst
    context:
      __title: button met optionele tekst
      sublabel: Gemeente Delft
  - name: button met optionele tekst selected
    context:
      __title: button met optionele tekst selected
      count: 1
      sublabel: Gemeente Delft
  - name: button met optionele tekst multiple selected
    context:
      __title: button met optionele tekst multiple selected
      count: 99
      sublabel: Gemeente Delft
  - name: button met optionele tekst disabled
    context:
      __title: button met optionele tekst disabled
      disabled: true
      sublabel: Gemeente Delft
