notes: |
  Toont navigatie-tabs. Gebaseerd op de Bootstrap `nav-tabs` component.

  Speciale aandacht voor de `.disabled` modifier:
    * Scriptend moet ervoor gezorgd worden dat de `a` niet meer reageert;
    * Let op de tabindex bij een disabled tabblad;

  Zie ook https://getbootstrap.com/docs/3.3/components/#nav-disabled-links.
status: ready
collated: true
context:
  __title: Two tabs
  tabs:
    - label: Tab 1
      url: '#'
      modifiers: active
    - label: Tab 2
      url: '#'
      modifiers: disabled
variants:
  - name: Three tabs
    context:
      __title: Three tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
        modifiers: disabled

  - name: Four tabs
    context:
      __title: Four tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
        modifiers: disabled

  - name: Five tabs
    context:
      __title: Five tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
        modifiers: disabled

  - name: Six tabs
    context:
      __title: Six tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
        modifiers: disabled

  - name: Seven tabs
    context:
      __title: Seven tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
      - label: Tab 7
        url: '#'
        modifiers: disabled

  - name: Eight tabs
    context:
      __title: Eight tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
      - label: Tab 7
        url: '#'
      - label: Tab 8
        url: '#'
        modifiers: disabled

  - name: Nine tabs
    context:
      __title: Nine tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
      - label: Tab 7
        url: '#'
      - label: Tab 8
        url: '#'
      - label: Tab 9
        url: '#'
        modifiers: disabled

  - name: Ten tabs
    context:
      __title: Ten tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
      - label: Tab 7
        url: '#'
      - label: Tab 8
        url: '#'
      - label: Tab 9
        url: '#'
      - label: Tab 10
        url: '#'
