status: ready
collated: true
context:
  __title: Spinner 24px groot, onbepaalde tijd
  status: Een moment geduld alstublieft.
  id: small
variants:
- name: spinner-medium-infinite
  context:
    __title: Spinner 32px groot, onbepaalde tijd
    id: medium
- name: spinner-large-infinite
  context:
    __title: Spinner 48px groot, onbepaalde tijd
    id: large
- name: spinner-small-5s
  context:
    __title: Spinner 24px groot, 5 seconden
    status: Een moment geduld alstublieft.
    id: small-5s
    time: 5s
- name: spinner-medium-5s
  context:
    __title: Spinner 32px groot, 5 seconden
    id: medium-5s
    time: 5s
- name: spinner-large-5s
  context:
    __title: Spinner 48px groot, 5 seconden
    id: large-5s
    time: 5s
