notes: |
status: ready
context:
  modifier: table
  caption: Overzicht bronnen
  columnHeaders:
    - title: Bron
      sorteerbaar: true
    - title: Uitleg 
  rowContent:
    - bron: AQUO
      uitleg: In de Aquo-begrippenset staan begrippen, die worden gebruikt in de watersector.   
    - bron: BesluitActiviteitenLeefomgeving
      uitleg: Besluit Activiteiten Leefomgeving
    - bron: BesluitBouwwerkenLeefomgeving
      uitleg: Besluit Bouwwerken Leefomgeving
    - bron: BesluitKwaliteitLeefomgeving
      uitleg: Besluit Kwaliteit Leefomgeving
    - bron: Omgevingsbesluit  
      uitleg: Omgevingsbesluit
    - bron: Omgevingswet
      uitleg: Omgevingswet
    - bron: VNGBegrippenkaderGemeenten
      uitleg: Dit is de bron waar alle VNG begrippen op gebaseerd zijn.