notes: |
  Een formulier begint altijd met een `form`-element. Als een `form`-element ongewenst is kan een element met de class `.form` worden ingezet. Elke _textuele_ `input` **en** `select` zit in een `.form-group`. Elk formulier onderdeel is een _groep_ met een `label`.

  Alle elementen zitten in een `fieldset` met een `legend`. De legend kan verborgen worden met een `.sr-only`. De form submit (en eventueel een form reset) staat _buiten_ de fieldset.

  * Een eventuele toelichting zit in een `p.dso-help-block`. Als er een toelichting is, dient deze met een `@aria-describedby` aan de input gekoppeld te worden.
  * Een label bij een _textuele_ `input` **of** `select` eindigt altijd met een dubbele punt.

  Buttons worden uitgelijnd afhankelijk van de context:

  * Buttons worden gesorteerd op belangrijkheid van rechts naar links, met de primaire actie aan de rechterkant. Wanneer knoppen gebruikt worden om door een reeks schermen te navigeren, wordt de primaire knop rechts uitgelijnd en de 'terug' actie helemaal links om de navigatie visueel te ondersteunen.
  * Uitgezonderd zijn formulieren met één pagina en gerichte taken, buttons links uitlijnen en sorteren op belangrijkheid van links naar rechts.

  De uitzonderingen worden met de modifier `.dso-single-page` op een `form` of `.form` ingezet.

  #### Extra:
  * https://getbootstrap.com/docs/3.3/css/#forms
  * [H91: Using HTML form controls and links](https://www.w3.org/TR/WCAG20-TECHS/H91)
status: ready
default: form-vertical
context:
  formLegend: Vertical Form
  fieldsets:
  - legend: Contact
    groups:
    - id: voornaam
      inputType: input
      type: text
      label: Voornaam
      required: true
    - id: achternaam
      inputType: input
      type: text
      label: Achternaam
      helpText: Mag ook de familienaam zijn
    - inputType: static
      label: Geslacht
      value: Man
    - id: geboortedatum
      inputType: input
      type: text
      label: Geboortedatum
      inputIcon: calendar
    - id: email
      inputType: input
      type: text
      label: E-mailadres
      required: true
    - id: password
      inputType: input
      type: text
      label: Wachtwoord
    - id: password_bevestig
      inputType: input
      type: text
      label: Wachtwoord (bevestig)
    - id: nieuwsbrief
      inputType: confirm
      label: Stuur mij de maandelijkse nieuwsbrief
      helpText: Uw gegevens zullen niet worden gedeeld met derden
