notes: |
  De rollen `tablist`, `tab` en `tabpanel` tonen de elementen `<ul>`, `<a>` en `<div>` als een verzameling tabbladen en bijbehorende tabbladen in de toegankelijkheidsboom.

  De rol `presentation` voorkomt dat de `<li>`-elementen in kaart worden gebracht in de toegankelijkheidsboom.

  Het `aria-selected` kenmerk geeft aan welk tabblad momenteel is geselecteerd.

  Het `tabindex`-attribuut zorgt ervoor dat alleen het momenteel geselecteerde tabblad in de tabvolgorde wordt opgenomen.

  Het `hidden` attribuut verbergt alles behalve het momenteel weergegeven tabpaneel voor weergave.

  Het kenmerk `aria-controls` legt een relatie tussen elk tabblad en het bijbehorende tabblad.

  Het kenmerk `aria-labelledby` hergebruikt de naam van het tabblad als de toegankelijke naam van het bijbehorende tabblad.

  De `click`- en `keydown`- event listeners leggen de verwachte muis- en toetsenbordgebeurtenissen vast voor het activeren van de tabbladen. Scriptend moet ervoor gezorgd worden dat de a daarin niet meer reageert.
  Zie ook https://getbootstrap.com/docs/3.3/components/#nav-disabled-links.

status: ready
collated: true
context:
  __title: Two tabs
  tabs:
    - label: Tab 1
      url: '#'
      modifiers: active
    - label: Tab 2
      url: '#'
      modifiers: disabled
variants:
  - name: Three tabs
    context:
      __title: Three tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
        modifiers: disabled

  - name: Four tabs
    context:
      __title: Four tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
        modifiers: disabled

  - name: Five tabs
    context:
      __title: Five tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
        modifiers: disabled

  - name: Six tabs
    context:
      __title: Six tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
        modifiers: disabled

  - name: Seven tabs
    context:
      __title: Seven tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
      - label: Tab 7
        url: '#'
        modifiers: disabled

  - name: Eight tabs
    context:
      __title: Eight tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
      - label: Tab 7
        url: '#'
      - label: Tab 8
        url: '#'
        modifiers: disabled

  - name: Nine tabs
    context:
      __title: Nine tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
      - label: Tab 7
        url: '#'
      - label: Tab 8
        url: '#'
      - label: Tab 9
        url: '#'
        modifiers: disabled

  - name: Ten tabs
    context:
      __title: Ten tabs
      tabs:
      - label: Tab 1
        url: '#'
        modifiers: active
      - label: Tab 2
        url: '#'
      - label: Tab 3
        url: '#'
      - label: Tab 4
        url: '#'
      - label: Tab 5
        url: '#'
      - label: Tab 6
        url: '#'
      - label: Tab 7
        url: '#'
      - label: Tab 8
        url: '#'
      - label: Tab 9
        url: '#'
      - label: Tab 10
        url: '#'
