notes: |
status: ready
context:
  steps:
    title: 4. Resultaat
    step: Stap 4 van 4
  alert:
    modifier: warning
    sronly: "Waarschuwing:"
    message: Bedrijf veranderen of uitbreiden? Dan hoeft u voor bestaande milieubelastende activiteiten die niet veranderen geen vergunning aan te vragen, melding te doen of informatie te geven.
  werkzaamheden:
    items:
      - modifier: warning
        label: U vraagt een <strong>vergunning</strong> aan voor milieubelastende activiteit gereguleerd in het omgevingsplan.
        subItems:
          - <strong>Let op:</strong> Kan er in één van de opslagtanks meer dan 13.000 liter propaan of propeen? Dan hoeft u geen aparte vergunning aan te vragen voor het opslaan in meer dan twee opslagtanks.
      - modifier: warning
        label: U vraagt een <strong>vergunning</strong> aan voor milieubelastende activiteit gereguleerd bij AMvB.
  tankstation:
    items:
      - modifier: warning
        label: U vraagt een <strong>vergunning</strong> aan voor milieubelastende activiteit gereguleerd bij AMvB.
  wasstraat:
    items:
      - modifier: danger
        label: Voor milieubelastende activiteit gereguleerd bij AMvB is op dit moment geen vragenlijst van het rijk beschikbaar. <strong>Neem contact op met uw gemeente</strong> om te weten wat u moet doen.
