notes: |
status: ready
context:
  steps:
    title: 2. Locatie
    step: Stap 1/7
  filter:
    placeholder: Zoek een adres
    icon: true
    label: Adres
    asideButtons:
    - type: link
      modifier: link
      label: Vorige stap
      icon: chevron-left
    buttons:
    - type: submit
      modifier: primary
      label: Volgende stap
      iconAfter: chevron-right
