notes: |
status: ready
context:
  steps:
    title: 3. Kies activiteiten
    step: Stap 3/7
  alert:
    status: info
    message: Hulp nodig bij kiezen? Doe dan eerst de <a href="#">Vergunningscheck</a>.
  shoppingcart:
    items:
      - label: Andere activiteiten dan kabels en leidingen in het beperkingengebied van een Rijksweg - Aanvraag vergunning
        additive: 1
    collapsed: true
  search:
    inputType: search-bar
    label: Zoek uw activiteiten
    placeholder: Bijvoorbeeld bouwactiviteiten
    icon: true
    id: filter_activiteiten
    hideSearchButton: true
    clearButton: true
  formFacets:
  - legend: Filters
    groups:
    - id: facets 
      inputType: checkboxes
      label: Maak een keuze
      options:
      - value: 1
        label: een
        id: checkbox_1
      - value: 2
        label: twee
        id: checkbox_2
      - value: 3
        label: drie
        id: checkbox_3
  listButtons:
  - type: button
    label: Andere activiteiten dan kabels en leidingen in het beperkingengebied van een Rijksweg - Aanvraag vergunning
    sublabel: 'Rijk'
    count: '1'
  - type: button
    label: Bouwen dakkapel - Aanvraag vergunning
    sublabel: Gemeente
  - type: button
    label: In stand houden van bouwwerken - Melding
    sublabel: Gemeente
  - type: button
    label: Milieubelastende activiteit - Aanvraag vergunning
    sublabel: Gemeente
  - type: button
    label: Opslaan van vloeistoffen in opslagtanks of in tankcontainers of verpakkingen gebruikt als opslagtank  - Aanvraag vergunning
    sublabel: Rijk
  asideButtons:
  - type: link
    modifier: link
    label: Vorige stap
    icon: chevron-left
  buttons:
  - type: submit
    modifier: primary
    label: Volgende stap
    iconAfter: chevron-right
