notes: |
status: ready
context:
  steps:
    title: 3. Kies activiteiten
    step: Stap 3/7
  alert:
    status: info
    message: Hulp nodig bij kiezen? Doe dan eerst de <a href="#">Vergunningscheck</a>.
  shoppingcart:
    items:
      - label: Andere activiteiten dan kabels en leidingen in het beperkingengebied van een Rijksweg - Aanvraag vergunning
        additive: 1
    collapsed: true
  search:
    inputType: search-bar
    label: Zoek uw activiteiten
    placeholder: Bijvoorbeeld bouwactiviteiten
    icon: true
    id: filter_activiteiten
    hideSearchButton: true
    clearButton: true
    searchBar:
        placeholder: Bijvoorbeeld bouwactiviteiten
        icon: true
        id: filter_activiteiten
        label: Zoek uw activiteiten
        noLabel: true
        hideSearchButton: true
        clearButton: true
  listbutton:
  - type: button
    label: Milieubelastende activiteit - Melding
    sublabel: Gemeente Delft
  - type: button
    label: Milieubelastende activiteit - Melding
    sublabel: Gemeente Delft
    asideButtons:
    - type: link
      modifier: link
      label: Vorige stap
      icon: chevron-left
    buttons:
    - type: submit
      modifier: primary
      label: Volgende stap
      iconAfter: chevron-right
