notes: |
  Class `singlestep` lijnt de buttons links uit.
  Class `dso-multistep` icm `dso-form-default` lijnt de buttons rechts uit.
  Class `dso-multistep` icm `dso-form-paging` lijnt de eerste button links, de tweede button rechts uit.
collated: true
status: wip
context:
  __title: Formulier met enkel scherm
  formStyle: singlestep
  buttons:
    - modifier: primary
      label: Primaire actie
      type: button
variants:
  - name: Formulier met enkel scherm en annuleren optie
    context:
      __title: Formulier met enkel scherm en annuleren optie
      formStyle: singlestep
      buttons:
        - modifier: primary
          label: Primaire actie
          type: button
        - label: Secundaire actie
          modifier: link
          type: button
  - name: Groot formulier met meerdere secties en annuleren optie
    context:
      __title: Groot formulier met meerdere secties en annuleren optie
      pagingStyle: default
      formStyle: multistep
      buttons:
        - label: Secundaire actie
          modifier: link
          type: button
        - label: Primaire actie
          modifier: primary
          type: button
  - name: Groot formulier met meerdere stappen
    context:
      __title: Groot formulier met meerdere stappen
      pagingStyle: paging
      formStyle: multistep
      buttons:
        - label: Vorige
          modifier: link
          type: button
          icon: chevron-left
        - label: Volgende
          modifier: primary
          type: button
  - name: Groot formulier met meerdere stappen en annuleren optie
    context:
      __title: Groot formulier met meerdere stappen en annuleren optie
      pagingStyle: paging
      formStyle: multistep
      buttons:
        - label: Vorige
          modifier: link
          type: button
          icon: chevron-left
        - label: Secundaire actie
          modifier: link
          type: button
        - label: Volgende
          modifier: primary
          type: button
