label: Lay-out
notes: |
  Voor meer informatie zie [Bootstrap Grid system](https://getbootstrap.com/docs/3.3/css/#grid) documentatie
status: ready
collated: true
context:
  rows:
    - columns:
      -
        - xs-12
    - columns:
      -
        - xs-6
      -
        - xs-6
    - columns:
      -
        - xs-4
      -
        - xs-4
      -
        - xs-4
    - columns:
      -
        - xs-3
      -
        - xs-3
      -
        - xs-3
      -
        - xs-3
    - columns:
      -
        - xs-12
        - sm-12
        - md-10
        - md-offset-1
        - lg-8
        - lg-offset-2
