status: ready
collated: true
context:
  title: Standaard panel
  body: Panel content
  modifier: default
variants:
  - name: footer
    context:
      title: H1 Panel title
      header: h1
      footer: Panel footer
  - name: primary
    context:
      title: Panel contextual primary
      footer: Panel footer
      modifier: primary
  - name: success
    context:
      title: Panel contextual success
      footer: Panel footer
      modifier: success
  - name: info
    context:
      title: Panel contextual info
      footer: Panel footer
      modifier: info
  - name: warning
    context:
      title: Panel contextual warning
      footer: Panel footer
      modifier: warning
  - name: danger
    context:
      title: Panel contextual danger
      footer: Panel footer
      modifier: danger
