notes: |
  De class `.dso-scripted-height` verwijdert op `.dso-body` in de large viewport de `max-height`-property.

  Modals zijn schermelementen die de hoofdflow van de gebruiker onderbreken. Goed doordachte inhoud en het juiste verschijningsmoment van modals zorgen ervoor dat het bezoek van de gebruiker intuïtief verloopt en de ervaring biedt die hij of zij verwacht. Het zal helpen bij het vermijden van de constante storingsfactor van een misplaatste modal (verkeerd gebruik van een modal).

  ## Wanneer te gebruiken:

  - **Onderbreking:** de gebruiker dwingen een beslissing te nemen of een taak te voltooien voor een belangrijk deel van hun workflow. Stel jezelf de vraag, "wil ik de gebruiker echt onderbreken?"
  - **Feedback of correctie:** beslissingen bevestigen. Bijvoorbeeld: bij een "Weet je het zeker?"-moment.
  - **Aandacht punt:** de focus van de gebruiker expliciet richten op een enkel stuk inhoud, of het nu een afbeelding, artikel of video is.

  {% render '@lib-frame', {path: ('/components/preview/dialog--valid' | path), element: '.dso-dialog'} %}

  ## Wanneer _niet_ te gebruiken

  Modals zijn bedoeld om belangrijke bevestigingen en beslissingen te benadrukken. Het is niet wenselijk ingewikkelde interacties in een modal stoppen. Zoals een formulier, of een uitgebreide zoeklijst.

  Een modal dient alleen gebruikt te worden voor simpele interacties. Probeer ingewikkelde interacties op andere manieren in een pagina te verwerken.

  {% render '@lib-frame', {path: ('/components/preview/dialog--invalid' | path), element: '.dso-dialog'} %}

  ## Gedrag en toegankelijkheid

  1. Wanneer een modal geactiveerd wordt moet de focus verplaatst worden naar het modal. Vervolgens binnen het modal naar het eerste interactieve element.
  2. Een modal moet een accessible naam hebben en zowel visueel als in de code, voor screenreaders, zichzelf presenteren als een modal.
  3. De volgende standaard methodes moeten beschikbaar zijn voor de gebruiker om een modal te sluiten:

      * Close button, dit mag het kruisje rechtsboven zijn of een annuleer knop in de modal footer;
      * De escape knop sluit een modal, zodat toetsenbord gebruikers ook een modal kunnen sluiten;
      * Buiten een modal klikken sluit ook een modal;

  4.  Als een modal actief is kan een gebruiker nog altijd naar de adresbalk van de browser navigeren.
  5.  Wanneer een modal actief is moeten alle elementen die bedekt worden door het modal venster met overlay niet toegankelijk zijn. Dit betekent dat als de tabkey gebruikt wordt de focus binnen de modal blijft en het niet mogelijk is content buiten de modal te benaderen.
  6.  Wanneer een modal dialog gesloten wordt dan moet de focus terug gaan naar het element dat de modal heeft geopend.

  Dit staat gebruikers toe om de verder te gaan waar ze gebleven waren. Als een modal niet is aangeroepen door een actie van een gebruiker dan moet de focus geplaatst worden op een logische locatie. Als een modal bijv. 'onPageLoad' wordt aangeroepen dan is het beste om na het sluiten van een modal de virtuele focus aan het begin van de pagina te zetten.
status: ready
default: modal
context:
  body: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
  dialog:
    id: modal-no-close
    heading: Activiteit toevoegen
    buttons:
      - name: confirmButton
        type: submit
        modifier: primary
        label: Toevoegen
      - name: cancelButton
        type: button
        modifier: link
        label: Annuleren
variants:
  - name: modal-close
    label: Closable
    context:
      dialog:
        id: modal-close
  - name: modal-single-submit
    label: Single submit
    context:
      dialog:
        id: modal-single-submit
        buttons:
        - name: confirmButton
          type: submit
          modifier: primary
          label: Indienen
  - name: modal-single-cancel
    label: Single cancel
    context:
      dialog:
        id: modal-single-cancel
        buttons:
        - name: cancelButton
          type: button
          modifier: link
          label: Annuleren
  - name: modal-steps
    label: Steps
    context:
      dialog:
        id: modal-steps
        buttons:
        - name: previousButton
          type: button
          modifier: default
          label: Vorige
        - name: nextButton
          type: button
          modifier: default
          label: Volgende
        - name: cancelButton
          type: button
          modifier: link
          label: Annuleren
  - name: modal-confirm
    label: Confirm
    context:
      body: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
      dialog:
        id: modal-confirm
        confirm: true
        buttons:
        - name: yesButton
          type: button
          modifier: default
          label: Ja
        - name: noButton
          type: button
          modifier: default
          label: Nee
  - name: modal-scripted-height
    label: No max height
    context:
      body: |
        What is Lorem Ipsum?
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        Why do we use it?
        It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
        Where does it come from?
        Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
        The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
        Where can I get some?
        There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
      noMaxHeight: true
      dialog:
        id: modal-scripted-height
