context:
  formWithHelpText:
    fieldsets:
    - legend: Contact
      legendScreenreaderOnly: true
      groups:
      - id: name
        inputType: input
        type: text
        label: Naam
        helpText: Instructie tekst buiten een tekstveld.
  formWithEmptyRequiredField:
    fieldsets:
    - legend: Contact
      legendScreenreaderOnly: true
      groups:
      - id: name2
        inputType: input
        type: text
        label: Naam
        required: true
        state: invalid
        helpText: Instructie tekst buiten een tekstveld.
        errorText: Verplicht veld niet gevuld
