notes: |
status: ready
context:
  search:
    inputType: search-bar
    label: Zoek uw activiteiten
    value: Situatieschets
    icon: true
    id: filter_activiteiten
    buttonLabel: Zoeken
    clearButton: true
    hiddenLabel: true
  links1:
    links:
      - label: Kan ik de gegevens van mijn vergunningcheck meenemen naar aanvragen?
        url: '#'
      - label: Wie kan een aanvraag indienen?
        url: '#'
      - label: Hoe moet ik een aanvraag aanvullen?
        url: '#'
