notes: |
status: ready
context:
  search:
    inputType: search-bar
    label: Zoek uw activiteiten
    value: Situatieschets
    icon: true
    id: filter_activiteiten
    buttonLabel: Zoeken
    clearButton: true
    hiddenLabel: true
  links1:
    links:
      - label: Lorem ipsum dolor sit amet, consectetur adipiscing elit?
        url: '#'
      - label: Sed do eiusmod tempor?
        url: '#'
      - label: Excepteur sint occaecat cupidatat?
        url: '#'
      - label: Lorem ipsum dolor sit amet, consectetur adipiscing elit?
        url: '#'
      - label: Sed do eiusmod tempor?
        url: '#'
      - label: Excepteur sint occaecat cupidatat?
        url: '#'
      - label: Lorem ipsum dolor sit amet, consectetur adipiscing elit?
        url: '#'
      - label: Sed do eiusmod tempor?
        url: '#'
      - label: Excepteur sint occaecat cupidatat?
        url: '#'
  links2:
    links:
      - label: Lorem ipsum dolor sit amet, consectetur adipiscing elit?
        url: '#'
      - label: Sed do eiusmod tempor?
        url: '#'
      - label: Excepteur sint occaecat cupidatat?
        url: '#'
      - label: Lorem ipsum dolor sit amet, consectetur adipiscing elit?
        url: '#'
      - label: Sed do eiusmod tempor?
        url: '#'
      - label: Excepteur sint occaecat cupidatat?
        url: '#'
      - label: Lorem ipsum dolor sit amet, consectetur adipiscing elit?
        url: '#'
      - label: Sed do eiusmod tempor?
        url: '#'
      - label: Excepteur sint occaecat cupidatat?
        url: '#'
