notes: |
status: ready
context:
  search:
    inputType: search-bar
    label: Zoek uw activiteiten
    placeholder: Bijvoorbeeld Hoe moet ik inloggen
    icon: true
    id: filter_activiteiten
    buttonLabel: Zoeken
    clearButton: true
    hiddenLabel: true
  links1:
    links:
      - label: Toestemming nodig
        url: '#'
      - label: Vergunningcheck
        url: '#'
      - label: Maatregelen op maat
        url: '#'
  links2:
    links:
      - label: Aanvraag of melding indienen
        url: '#'
      - label: Bijlagen
        url: '#' 
      - label: Machtigen
        url: '#'
      - label: Bezwaar en beroep
        url: '#'
  links3:
    links:
      - label: Regels op de kaart
        url: '#'
      - label: Omgevingsdocumenten
        url: '#' 
      - label: Terminologie
        url: '#'
  links4:
    links:
      - label: Plannen in ontwikkeling
        url: '#'
      - label: Bezwaar maken
        url: '#' 
      - label: Notificaties ontvangen
        url: '#'
  links5:
    links:
      - label: Inloggen
        url: '#'
      - label: Account
        url: '#' 
      - label: Storingen en onderhoud
        url: '#'
