notes: |
status: ready
context:
  search:
    inputType: search-bar
    label: Zoek uw activiteiten
    value: Situatieschets
    icon: true
    id: filter_activiteiten
    buttonLabel: Zoeken
    clearButton: true
    hiddenLabel: true
