context:
  navs:
    - items:
      - label: documentatie
      - label: Introductie
        items:
          - label: Voor ontwerpers
          - label: Voor ontwikkelaars
            active: true
          - label: Toegankelijkheid
      - label: Versies
        items:
          - label: Alle versies
    - items:
      - label: fundament
      - label: Grid
      - label: Kleuren
      - label: Logo / favicon
      - label: Typografie
    - items:
      - label: componenten
      - label: Accordion
      - label: Alerts
      - label: Badge
      - label: Breadcrumbs
      - label: Buttons
      - label: Conclusion
    - items:
      - label: voorbeelden
      - label: Aanvragen
      - label: Aanvragen upload bestanden
      - label: Accordion label
