context:
  navs:
    - label: Documentatie
      items:
      - label: Introductie
        items:
        - label: Voor ontwerpers
        - label: Voor ontwikkelaars
          active: true
        - label: Toegankelijkheid
      - label: Versies
        collapsed: true
        items:
        - label: Alle versies
    - label: Fundament
      items:
      - label: Grid
        items:
          - label: Bootstrap
            items:
            - label: Herkomst
              items:
              - label: Overwegingen
      - label: Kleuren
      - label: Logo / favicon
      - label: Typografie
    - label: Componenten
      items:
      - label: Accordion
      - label: Alerts
      - label: Badge
      - label: Breadcrumbs
      - label: Buttons
      - label: Conclusion
    - label: Voorbeelden
      items:
      - label: Aanvragen
      - label: Aanvragen upload bestanden
      - label: Accordion label
