meta:
  webComponent: dso-attachments-counter
  markup: false
notes: |
  De attachment counter is een teller voor bijlagen. Deze wordt getoond met het aantal bijlagen en het paperclip-icoon. Het geeft aan hoeveel bijlagen er zijn toegevoegd die bekeken of gedownload kunnen worden.

  ## Wanneer te gebruiken
  Gebruik de attachment counter bij elementen waar bestanden kunnen worden geüpload, gedownload en/of bekeken.

  ## Hoe te gebruiken
  Gebruik het paperclip-icoon in combinatie met een titel. Een attachment counter heeft geen interactie en is niet klikbaar of te verwijderen. De counter valt onder de statusmeldingen: 'indicatoren, validatoren en notificaties'.

  ## Gedrag en toegankelijkheid
  * De `sr-only`tekst "bijlage" is een tekstalternatief voor de paperclip, neem deze dus op.
  * Let op enkelvoud en meervoud: 1 bijlage, 2 bijlagen. Pas dit vanuit je javascript aan of gebruik eventueel de vorm bijlage(n)

  ## Component in context
  - [Accordion table]({{ '/components/detail/accordion-table' | docPath }})

context:
  __title: attachments counter
  count: 1
