notes: |
  Een help block staat altijd direct in de `.form-group`.
status: wip
collated: true
context:
  id: select_voorbeeld
  label: Select
  options:
    - optionType: Europees
      items:
        - value: alfa
          label: Alfa Romeo
        - value: fiat
          label: Fiat
        - value: marcedes
          label: Mercedes
          selected: true
        - value: volkswagen
          label: Volkswagen
variants:
  - name: input-focus
    context:
      id: group_input_focus
      type: text
      label: Select - Focus
      inputModifiers: " example-focus"
      options:
        - optionType: Europees
          items:
            - value: alfa
              label: Alfa Romeo
            - value: fiat
              label: Fiat
            - value: marcedes
              label: Mercedes
              selected: true
            - value: volkswagen
              label: Volkswagen
  - name: input-feedback
    context:
      id: group_input_feedback
      type: text
      label: Select - Feedback
      inputModifiers: " example-default"
      helpText: Deze producten worden allemaal gemaakt in een fabriek waar ook noten worden verwerkt
      options:
        - optionType: Europees
          items:
            - value: alfa
              label: Alfa Romeo
            - value: fiat
              label: Fiat
            - value: marcedes
              label: Mercedes
              selected: true
            - value: volkswagen
              label: Volkswagen
  - name: input-required
    context:
      id: group_input_required
      type: text
      label: Select - Verplicht
      required: true
      options:
        - optionType: Europees
          items:
            - value: alfa
              label: Alfa Romeo
            - value: fiat
              label: Fiat
            - value: marcedes
              label: Mercedes
              selected: true
            - value: volkswagen
              label: Volkswagen
  - name: input-ongeldig
    context:
      id: group_input_invalid
      type: text
      label: Select - Ongeldig
      inputModifiers: " invalid"
      required: true
      errorText: U heeft geen geldige waarde geselecteerd
      options:
        - optionType: Europees
          items:
            - value: alfa
              label: Alfa Romeo
            - value: fiat
              label: Fiat
            - value: marcedes
              label: Mercedes
              selected: true
            - value: volkswagen
              label: Volkswagen
  - name: input-ongeldig-feedback
    context:
      id: group_input_invalid-feedback
      type: text
      label: Select - Ongeldig / Feedback
      inputModifiers: " invalid"
      required: true
      errorText: Voer een geldig e-mailadres in
      helpText: Deze producten worden allemaal gemaakt in een fabriek waar ook noten worden verwerkt
      options:
        - optionType: Europees
          items:
            - value: alfa
              label: Alfa Romeo
            - value: fiat
              label: Fiat
            - value: marcedes
              label: Mercedes
              selected: true
            - value: volkswagen
              label: Volkswagen
  - name: input-uitleg
    context:
      id: group_input_explanation
      type: text
      label: Select - Uitleg
      inputModifiers: " example-default"
      helpIcon: true
      options:
        - optionType: Europees
          items:
            - value: alfa
              label: Alfa Romeo
            - value: fiat
              label: Fiat
            - value: marcedes
              label: Mercedes
              selected: true
            - value: volkswagen
              label: Volkswagen
