notes: |
  Een help block staat altijd direct in de `.form-group`.
status: wip
collated: true
context:
  id: textarea_voorbeeld
  label: Textarea
  rows: 5
variants:
  - name: textarea-focus
    context:
      id: group_input_focus
      type: text
      label: Textarea - Focus
      inputModifiers: " example-focus"
  - name: textarea-feedback
    context:
      id: group_input_feedback
      type: text
      label: Textarea - Feedback
      inputModifiers: " example-default"
      helpText: Minimaal 6 tekens waarvan 1 leesteken
  - name: textarea-required
    context:
      id: group_input_required
      type: text
      label: Textarea - Verplicht
      required: Minimaal 6 tekens waarvan 1 leesteken
  - name: textarea-ongeldig
    context:
      id: group_input_invalid
      type: text
      label: Textarea - Ongeldig
      inputModifiers: " invalid"
      required: true
      errorText: Minimaal 6 tekens waarvan 1 leesteken
  - name: textarea-ongeldig-feedback
    context:
      id: group_input_invalid-feedback
      type: text
      label: Textarea - Ongeldig / Feedback
      inputModifiers: " invalid"
      required: true
      errorText: Voer een geldig e-mailadres in
      helpText: Minimaal 6 tekens waarvan 1 leesteken
  - name: textarea-uitleg
    context:
      id: group_input_explanation
      type: text
      label: Textarea - Uitleg
      inputModifiers: " example-default"
      helpIcon: true
