notes: |
status: ready
context:
  menu:
    modifier: main
    items:
      - label: Home
      - label: Vergunningcheck
      - label: Aanvragen
        active: true
      - label: Regels op de kaart
      - label: Mijn Omgevingsloket
  breadcrumbs:
    crumbs:
      - label: Home
        url: '#'
      - label: Aanvragen
        url: '#'
      - label: Mijn project
        url: '#'
      - label: Aanvraag voorbereiden
        url: '#'
