status: wip
notes: |
  Breedte van het element wordt gedicteerd door de bootstrap class van het omliggende element.
context:
  columns:
    - modifier: col-md-3 col-sm-6 col-xs-12
      whitebox:
        title: Whitebox met counter
        description: Weet u al voor welke activiteiten u een vergunning moet aanvragen of een melding moet doen?
        count: 1
    - modifier: col-md-3 col-sm-6 col-xs-12
      whitebox:
        title: Whitebox met counter
        description: Weet u al voor welke activiteiten u een vergunning moet aanvragen of een melding moet doen?
        count: 2
    - modifier: col-md-3 col-sm-6 col-xs-12
      whitebox:
        title: Whitebox met counter
        description: Weet u al voor welke activiteiten u een vergunning moet aanvragen of een melding moet doen?
        count: 3
    - modifier: col-md-3 col-sm-6 col-xs-12
      whitebox:
        title: Whitebox met counter
        description: Weet u al voor welke activiteiten u een vergunning moet aanvragen of een melding moet doen?
        count: 4
    - modifier: col-md-3 col-sm-6 col-xs-12
      whitebox:
        title: Whitebox met counter
        description: Weet u al voor welke activiteiten u een vergunning moet aanvragen of een melding moet doen?
        count: 5
    - modifier: col-md-3 col-sm-6 col-xs-12
      whitebox:
        title: Whitebox met counter
        description: Weet u al voor welke activiteiten u een vergunning moet aanvragen of een melding moet doen?
        count: 6
    - modifier: col-md-3 col-sm-6 col-xs-12
      whitebox:
        title: Whitebox met icon
        description: Weet u al voor welke activiteiten u een vergunning moet aanvragen of een melding moet doen?
        icon: di di-check
        label: afgerond
    - modifier: col-md-3 col-sm-6 col-xs-12
      whitebox:
        title: Whitebox met icon
        description: Weet u al voor welke activiteiten u een vergunning moet aanvragen of een melding moet doen?
        icon: di di-check
        label: afgerond
    - modifier: col-md-3 col-sm-6 col-xs-12
      whitebox:
        title: Whitebox met icon
        description: Weet u al voor welke activiteiten u een vergunning moet aanvragen of een melding moet doen?
        icon: di di-check
        label: afgerond
    - modifier: col-md-3 col-sm-6 col-xs-12
      whitebox:
        title: Whitebox met icon
        description: Weet u al voor welke activiteiten u een vergunning moet aanvragen of een melding moet doen?
        icon: di di-check
        label: afgerond
    - modifier: col-md-3 col-sm-6 col-xs-12
      whitebox:
        title: Whitebox met icon
        description: Weet u al voor welke activiteiten u een vergunning moet aanvragen of een melding moet doen?
        icon: di di-check
        label: afgerond
    - modifier: col-md-3 col-sm-6 col-xs-12
      whitebox:
        title: Whitebox met icon
        description: Weet u al voor welke activiteiten u een vergunning moet aanvragen of een melding moet doen?
        icon: di di-check
        label: afgerond
