status: ready
collated: true
context:
  __title: default
  searchBar:
    id: input-text
    type: text
    clearButton: true
    hideSearchButton: true
    icon: true
    placeholder: Activiteit
    resultsMessage: 7 activiteiten
