status: ready
id: input-stepper
collated: true
context:
  __title: default
  label: Default
  type: stepper
  count: 99
  minusButtonLabel: Aantal verlagen
  plusButtonLabel: Aantal verhogen
variants:
- name: input-stepper-incative
  context:
    __title: Inactive
    label: Inactive input stepper
    count: 99
    minusButtonInactive: true
    minusButtonLabel: Aantal verlagen (disabled)
    plusButtonInactive: true
    plusButtonLabel: Aantal verhogen (disabled)
- name: input-stepper-minimum-limit
  context:
    __title: Minimum limit (optional)
    label: Input stepper with minimum limit
    count: 0
    minusButtonInactive: true
    minusButtonLabel: Aantal verlagen (disabled)
- name: input-stepper-maximum-limit
  context:
    __title: Maximum limit (optional)
    label: Input stepper with maximum limit
    count: 99
    plusButtonInactive: true
    plusButtonLabel: Aantal verhogen (disabled)
