status: ready
collated: true
context:
  __title: default
  id: input-text
  type: text
  label: Tekstveld
variants:
- name: input-email
  context:
    __title: Email
    __explanation:
    - Er is een <code>type="email"</code> beschikbaar die helpt bij het automatisch valideren van een veld.
    id: input-email
    type: email
    label: E-mailadres
    value: pieter@
- name: input-date
  context:
    __title: Datum
    __explanation:
    - Er is een <code>type="date"</code> beschikbaar die een native manier van het selecteren van een datum faciliteert.
    id: input-date
    type: date
    label: Datum
    value: "1970-07-03"
- name: input-password
  context:
    __title: Wachtwoord
    __explanation:
    - Er is een <code>type="password"</code> beschikbaar die het ingevoerde wachtwoord maskeert met bullets.
    id: input-password
    type: password
    label: Wachtwoord
    value: Welkom01
- name: input-url
  context:
    __title: URL
    __explanation:
    - Er is een <code>type="url"</code> beschikbaar. Afhankelijk van de browserondersteuning kan het url veld automatisch worden gevalideerd wanneer het wordt verzonden. Sommige smartphones herkennen het url type en voegen ".com" toe aan het toetsenbord om overeen te komen met de url-invoer..
    id: input-url
    type: url
    label: URL
    value: https://www.aandeslagmetdeomgevingswet.nl
- name: input-tel
  context:
    __title: Tel
    __explanation:
    - Er is een <code>type="tel"</code> beschikbaarvoor het bewerken van een regel met één regel voor het invoeren van een telefoonnummer.
    id: input-tel
    type: tel
    label: Telefoon
    value: 062451789
- name: input-text-invalid
  context:
    __title: Ongeldig
    __explanation:
    - Indien een input ongeldig is, dient er een <code>.dso-invalid</code> class
      gezet te worden op de div met de class <code>.dso-input</code>.
    id: input-text-invalid
    type: email
    label: E-mailadres
    required: true
    helpText: 'Bijvoorbeeld: email@email.nl'
    state: invalid
    errorText: Vul dit veld in.
- name: input-text-invalid-input
  context:
    __title: Ongeldig - Foutieve invoer
    __explanation:
    - Indien een input ongeldig is, dient er een <code>.dso-invalid</code> class
      gezet te worden op de div met de class <code>.dso-input</code>.
    id: input-text-invalid-input
    type: email
    label: E-mailadres
    value: thomas@
    required: true
    helpText: 'Bijvoorbeeld: email@email.nl'
    state: invalid
    errorText: Ongeldig e-mailadres ingevuld.
- name: input-text-valid
  context:
    __title: Geldig
    __explanation:
    - Indien een input ongeldig was en valide wordt gemaakt, dient de
      <code>.dso-invalid</code> class vervangen te worden door de class <code>.dso-valid</code>.
    id: input-text-valid
    type: email
    label: E-mailadres
    value: thomas@infoprojects.nl
    required: true
    state: valid
    helpText: 'Bijvoorbeeld: email@email.nl'
- name: input-text-placeholder
  context:
    __title: Placeholder
    id: input-text-placeholder
    label: Naam
    placeholder: Voornaam Achternaam
    required: true
- name: input-text-icon
  context:
    __title: Met icoon
    id: input-text-icon
    type: email
    label: E-mailadres
    inputIcon: at
- name: input-text-disabled
  context:
    __title: Disabled
    id: input-text-disabled
    label: Naam
    disabled: true
- name: input-text-readonly
  context:
    __title: Readonly
    id: input-text-readonly
    label: Naam
    readonly: true
- name: input-text-infobutton
  context:
    __title: Infobutton
    __explanation:
    - Toelichting ingeklapt
    id: input-text-infobutton
    type: email
    label: E-mailadres
    value: thomas@
    infoOpen: false
    infoButtonLabel: Toelichting bij vraag
    infoText: |
      Closed
- name: input-text-infobutton-open
  context:
    __title: Infobutton uitgeklapt
    __explanation:
    - Toelichting uitgeklapt
    id: input-text-infobutton-open
    type: email
    label: E-mailadres
    required: true
    infoOpen: true
    infoButtonLabel: Toelichting bij vraag
    infoText: |
      <h4>Heading 4</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
        Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
        Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
      </p>
