status: ready
id: input-number
collated: true
context:
  __title: default
  label: Default
  id: default
  type: number
  count: 99
  minusButtonLabel: Aantal verlagen
  plusButtonLabel: Aantal verhogen
variants:
- name: input-number-inactive
  context:
    __title: Inactive
    label: Inactive input number
    id: inactive
    count: 99
    minusButtonInactive: true
    minusButtonLabel: Aantal verlagen (disabled)
    plusButtonInactive: true
    plusButtonLabel: Aantal verhogen (disabled)
- name: input-number-minimum-limit
  context:
    __title: Minimum limit (optional)
    label: Input number with minimum limit
    id: minimum-limit
    count: 0
    minusButtonInactive: true
    minusButtonLabel: Aantal verlagen (disabled)
- name: input-number-maximum-limit
  context:
    __title: Maximum limit (optional)
    label: Input number with maximum limit
    id: maximum-limit
    count: 99
    plusButtonInactive: true
    plusButtonLabel: Aantal verhogen (disabled)
