context:
  versions:
    - label: v9.x
      items:
        - label: 9.4.0
        - label: 9.3.1
        - label: 9.3.0
        - label: 9.2.0
        - label: 9.1.0
        - label: 9.0.0
    - label: v8.x
      items:
        - label: 8.5.0
        - label: 8.4.1
        - label: 8.3.0
        - label: 8.2.0
        - label: 8.1.0
        - label: 8.0.1
        - label: 8.0.0
    - label: v7.x
      items:
        - label: 7.3.1
        - label: 7.3.0
        - label: 7.2.0
        - label: 7.1.0
        - label: 7.0.1
        - label: 7.0.0
    - label: v6.x
      items:
        - label: 6.0.1
        - label: 6.0.0
    - label: v5.x
      items:
        - label: 5.1.0
        - label: 5.0.0
    - label: v4.x
      items:
        - label: 4.0.1
    - label: v3.x
      items:
        - label: 3.1.1
        - label: 3.1.0-beta.0
        - label: 3.1.0-alpha.5
        - label: 3.1.0-alpha.4
        - label: 3.1.0-alpha.3
        - label: 3.1.0-alpha.2
        - label: 3.1.0-alpha.1
        - label: 3.1.0-alpha.0
        - label: 3.1.0
        - label: 3.0.1
        - label: 3.0.0-beta.0
        - label: 3.0.0-alpha.2
        - label: 3.0.0-alpha.1
        - label: 3.0.0-alpha.0
        - label: 3.0.0
    - label: v2.x
      items:
        - label: 2.0.0-beta.0
        - label: 2.0.0-alpha.2
        - label: 2.0.0-alpha.1
        - label: 2.0.0-alpha.0
        - label: 2.0.0
    - label: v1.x
      items:
        - label: 1.2.4
        - label: 1.2.3
        - label: 1.2.2
        - label: 1.2.1
        - label: 1.2.0-beta.0
        - label: 1.2.0-alpha.0
        - label: 1.2.0
        - label: 1.1.0
        - label: 1.0.6
        - label: 1.0.5
        - label: 1.0.4
        - label: 1.0.3
        - label: 1.0.2
        - label: 1.0.1
        - label: 1.0.0
