status: wip
notes: |
  Buttons geven acties aan die gebruikers kunnen ondernemen. Ze zijn makkelijk te herkennen en te vinden. Een goede button geeft duidelijk aan welke actie een gebruiker onderneemt door erop te klikken. Gebruik vorm en kleur om een button herkenbaar te maken voor de gebruiker.

  - Plaats buttons waar gebruikers ze verwachten en maak ze makkelijk vindbaar.
  - Let op de grootte van een button, een touch size van minimaal 44x44px en witruimte rondom.
  - Let op de positie en volgorde van de buttons, vooral als ze in groepen staan. Benadruk de buttons die de belangrijkste acties aangeven.
  - Gebruik een contrasterende kleur om een actieknop op te laten vallen.

  ## Hoe te gebruiken: primaire buttons

  Primaire buttons zijn de buttons waarmee gebruikers de belangrijkste taak op een pagina afmaken.

  Staat een gebruiker op het punt om een onomkeerbare actie te nemen door op een
  button te klikken? Dan is de annuleerbutton de primaire button. De gebruiker moet namelijk
  goed nadenken voordat hij reageert. Zo verkleint u de kans dat een gebruiker per ongeluk doorklikt.

  {% render '@lib-frame', {path: ('/components/preview/buttons-primary' | docPath)} %}
  

  - Tekst wit, Asap semibold 16.
  - De button heeft een rechthoekige grasgroene achtergrond (`#39870c`) met afgeronde hoeken
  van 4 pixels en een hoogte van 48 pixels.
  - Maximaal één keer per scherm gebruiken, tenzij dezelfde actie meerdere keren op het scherm voorkomt.
  - Voor gebruik in de header of een modal gelden andere regels. Daar mag tegelijk ook een
  primaire actie staan.
  - Als er geen primaire actie is, heeft een scherm ook geen primaire button nodig.

  ## Hoe te gebruiken: secundaire buttons

  {% render '@lib-frame', {path: ('/components/preview/buttons-default' | docPath)} %}

  - Tekst grasgroen, Asap semibold 16.
  - De button heeft een rechthoekige witte achtergrond met een omlijning van 1 pixel in
  grasgroen (`#39870c`), afgeronde hoeken van 4 pixels en een hoogte van 48 pixels.
  - Gebruik deze button als het niet om een primaire actie gaat en/of er geen hiërarchie in de buttons zit.

  ## Hoe te gebruiken: tertiaire buttons
  Gebruik tertiaire buttons voor overige acties. Dit zijn acties die wel belangrijk zijn, maar niet per se de belangrijkste actie op dat moment. Denk aan 'wijzigen' of 'toevoegen', als dat op dat moment niet de belangrijkste acties zijn.

  {% render '@lib-frame', {path: ('/components/preview/buttons-link' | docPath)} %}

  - Tekst grasgroen (`#39870c`), Asap semibold 16
  - En/of icoon in grasgroen (`#39870c`)

  ## Hoe te gebruiken: kleine buttons
  Voeg de class `.btn-sm` toe om buttons kleiner te maken. De grootte verandert dan van 48 pixels naar 30 pixels voor primaire en secundaire buttons.

  Standaard zijn primaire en secundaire buttons 48 pixels hoog en worden dan 30 pixels hoog.

  {% render '@lib-frame', {path: ('/components/preview/buttons-small' | docPath)} %}

  ## Hoe te gebruiken: buttons in sectieberichten

  Gebruik buttons in een sectiebericht om een actie uit te voeren.

  {% render '@lib-frame', {path: ('/components/preview/buttons-in-alerts' | docPath)} %}

  ## Gedrag en toegankelijkheid

  - Buttons die er hetzelfde uitzien, moeten overal dezelfde functionaliteit hebben.
  - De tekst op de button moet beschrijven wat de button doet. Zie hiervoor ook het hoofdstuk UI Copy.