status: ready
context:
  body: Inhoud
  dialog:
    id: modal-dialog
    heading: Modal dialoog
    buttons:
      - name: confirmButton
        type: button
        modifier: dso-primary
        label: OK
variants:
  - name: valid
    context:
      body: Weet u zeker dat u wilt uitloggen? Opgeslagen gegevens zijn terug te vinden in Mijn Omgevingsloket
      dialog:
        id: modal-dialog-valid-example
        heading: Uitloggen
        buttons:
          - name: confirmButton
            type: button
            modifier: dso-primary
            label: Ja
          - name: cancelButton
            type: button
            modifier: dso-tertiary
            label: Nee
  - name: invalid
    context:
      form:
        id: alle-activiteiten
        inputType: checkboxes
        label: Alle activiteiten
        options:
          - value: bouwactiviteit-vergunning
            label: Bouwactiviteit - Vergunning
          - value: brug-aanleggen-delfland-vergunning
            label: Brug aanleggen Delfland - Vergunning
          - value: sloopactiviteiten-informatie-overig
            label: Sloopactiviteiten - Informatie overig
          - value: sloopactiviteiten-melding
            label: Sloopactiviteiten - Melding
      dialog:
        id: modal-dialog-invalid-example
        heading: Activiteit toevoegen
        buttons:
          - name: confirmButton
            type: button
            modifier: dso-primary
            label: Toevoegen
          - name: cancelButton
            type: button
            modifier: dso-tertiary
            label: Annuleren
  - name: dialog-close
    hidden: true
    label: Closable
    context:
      __title: Closable
      dialog:
        id: modal-close
  - name: dialog-single-submit
    label: Single submit
    context:
      __title: Single submit
      dialog:
        id: modal-single-submit
        buttons:
        - name: confirmButton
          type: submit
          modifier: dso-primary
          label: Indienen
  - name: dialog-steps
    hidden: true
    label: Steps
    context:
      __title: Steps
      dialog:
        id: modal-steps
        buttons:
        - name: cancelButton
          type: button
          modifier: dso-tertiary
          label: Annuleren
        - name: previousButton
          type: button
          modifier: dso-secondary
          label: Vorige
        - name: nextButton
          type: button
          modifier: dso-secondary
          label: Volgende
