status: ready
name: highlightBox
notes: Standaard achtergrondkleur grijs, andere varianten geel (modifier <code>highlightbox-yellow</code>) en met grijze border (modifier <code>highlightbox-bordered</code>).
variants:
  - name: yellow
    context:
      dso-highlightbox-modifier: highlightbox-yellow
  - name: bordered
    context:
      dso-highlightbox-modifier: highlightbox-bordered
