status: ready
notes: Standaard achtergrondkleur grijs, andere varianten geel (modifier <code>dso-highlight-box-yellow</code>) en met grijze border (modifier <code>dso-highlight-box-bordered</code>).
variants:
  - name: yellow
    context:
      modifier: dso-highlight-box-yellow
  - name: bordered
    context:
      modifier: dso-highlight-box-bordered
  - name: white-drop-shadow
    context:
      modifier: dso-white dso-drop-shadow
  - name: Step indicator
    context:
      modifier: dso-yellow
      step: 2
  - name: Icon indicator
    context:
      modifier: dso-yellow
      icon: plus
      label: Plus

