notes: |
  Een link lijst heeft andere styling (donkergrijze linkkleur en iconen) op een gekleurde achtergrond: bv. in een highlight-box en in de footer.
status: ready
context:
  links:
    - label: Externe link
      url: '#'
      modifier: extern
    - label: Download link
      url: '#'
      modifier: download
    - label: Interne link
      url: '#'
