status: ready
context:
  links:
    - label: Externe link
      url: '#'
      modifier: extern
    - label: Download link
      url: '#'
      modifier: download
    - label: Interne link
      url: '#'
