status: ready
default: modal
context:
  id: modal-no-close
  heading: Activiteit toevoegen
  body: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
  buttons:
    - name: confirmButton
      type: submit
      modifier: primary
      label: Toevoegen
    - name: cancelButton
      type: button
      modifier: link
      icon: icon fas fa-times
      label: Annuleren
  fieldsets:
  - legend: Contact
    groups:
    - id: voornaam
      inputType: input
      type: text
      label: Voornaam
      required: true
    - id: achternaam
      inputType: input
      type: text
      label: Achternaam
      helpText: Mag ook de familienaam zijn
    - inputType: static
      label: Geslacht
      value: Man
    - id: geboortedatum
      inputType: input
      type: text
      label: Geboortedatum
      inputIcon: fas fa-calendar
    - id: email
      inputType: input
      type: text
      label: E-mailadres
      required: true
    - id: password
      inputType: input
      type: text
      label: Wachtwoord
    - id: password_bevestig
      inputType: input
      type: text
      label: Wachtwoord (bevestig)
    - id: nieuwsbrief
      inputType: confirm
      label: Stuur mij de maandelijkse nieuwsbrief
      helpText: Uw gegevens zullen niet worden gedeeld met derden
  submitButton:
    type: submit
    modifier: primary
    label: Verstuur
notes: |
  De class `.dso-scripted-height` verwijdert op `.dso-body` in de large viewport de `max-height`-property.
variants:
  - name: modal-close
    label: Closable
    context:
      id: modal-close
  - name: modal-single-submit
    label: Single submit
    context:
      id: modal-single-submit
      buttons:
      - name: confirmButton
        type: submit
        modifier: primary
        label: Indienen
  - name: modal-single-cancel
    label: Single cancel
    context:
      id: modal-single-cancel
      buttons:
      - name: cancelButton
        type: button
        modifier: link
        icon: icon fas fa-times
        label: Annuleren
  - name: modal-steps
    label: Steps
    context:
      id: modal-steps
      buttons:
      - name: previousButton
        type: button
        modifier: default
        label: Vorige
      - name: nextButton
        type: button
        modifier: default
        label: Volgende
      - name: cancelButton
        type: button
        modifier: link
        icon: icon fas fa-times
        label: Annuleren
  - name: modal-confirm
    label: Confirm
    context:
      id: modal-confirm
      confirm: true
      body: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.
      buttons:
      - name: yesButton
        type: button
        modifier: default
        label: Ja
      - name: noButton
        type: button
        modifier: default
        label: Nee
  - name: modal-scripted-height
    label: No max height
    context:
      id: modal-scripted-height
      body: |
        What is Lorem Ipsum?
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        Why do we use it?
        It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).
        Where does it come from?
        Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
        The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.
        Where can I get some?
        There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
      noMaxHeight: true
