notes: De class `cta-primary` en `cta-default` kunnen alleen op elementen van het type `a` of `button` geplaatst worden
status: wip
collated: true
default: cta-button
variants:
  - name: cta-button
    context:
      button: true
      value: Volgende
  - name: cta-button-disabled
    context:
      button: true
      value: Volgende
  - name: cta-button-icon
    context:
      button: true
      value: Volgende
  - name: cta-button-anchor
    context:
      anchor: true
      value: Volgende
      url: "#"
