context:
  formWithIncorrectField:
    formLegend: Voorbeeld
    fieldsets:
    - legend: Contact
      legendScreenreaderOnly: true
      groups:
      - id: email
        inputType: input
        type: email
        label: E-mailadres
        value: piet@
        state: invalid
        errorText: Er is geen geldig e-mailadres ingevuld. Controleer of het e-mailadres een @ en een punt bevat, en of er geen spaties in staan.
