notes: |
  Dit component ondersteund twee verschillende manieren voor het maken van een upload knop:
  * Een `input[type="file"]` met een `label` element
  * Een `button` element

  Zie de comments in de HTML. Het gebruik van een `input[type="file"]` is semantisch correcter en voorkomt mogelijke _clickjacking_ warnings in Firefox. Het afhandelen van de upload kan aan `onchange` worden gehangen.

  https://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/

context:
  id: tekeningen
  description: Geef een tekening van de nieuwe situatie in 1:100. Een situatietekening geeft een schets van de bestaande en de nieuwe situatie met daarop duidelijk de maatvoering en de schaalaanduiding (1:100).
  files:
    - filename: Schetsen_en_foto's_1.pdf
    - filename: Bijlagen_hoveniersbedrijf_de_heggeschaar_hoveniers.jpg
      confidential: true
