notes: |
  Een radio group heeft een root element `fieldset.form-group`, en geen `div.form-group`.
status: ready
collated: true
context:
  __title: default
  id: input-radio
  label: Group radios - Default
  helpText: de meeste mensen kiezen benzine maar vanaf 50000 km per jaar is diesel goedkoper
  options:
  - value: 1
    label: benzine
    checked: true
  - value: 2
    label: diesel
variants:
- name: input-radio-required
  context:
    __title: required
    __explanation:
    - Een verplichte keuze wordt in de markup aangegeven met <code>.dso-required</code>
      op de <code>.form-group.dso-radios</code>
    - Radiobuttons hebben (net zoals checkboxen) een <code>fieldset.form-group</code> als
      root element, geen <code>div.form-group</code>
    id: input-radio-required
    label: Group radios - Required
    required: true
- name: input-radio-invalid
  context:
    __title: invalid
    __explanation:
    - Indien een radio groep ongeldig is, dient er een <code>.dso-invalid</code>
      class gezet te worden op de div met de class <code>.dso-radios</code>.
    id: input-radio-invalid
    label: Group radios - Invalid
    required: true
    state: invalid
    errorText: Maak een keuze.
    options:
    - value: 1
      label: benzine
    - value: 2
      label: diesel
- name: input-radio-valid
  context:
    __title: valid
    __explanation:
    - Indien een radio groep ongeldig was en valide wordt gemaakt, dient de <code>.dso-invalid</code> class vervangen te worden door de class <code>.dso-valid</code>.
    id: input-radio-valid
    label: Group radios - Valid
    required: true
    state: valid
    options:
    - value: 1
      label: benzine
      checked: true
    - value: 2
      label: diesel
- name: input-radio-disabled
  context:
    __title: disabled
    id: input-radio-disabled
    label: Group radios - Disabled
    required: true
    state: valid
    options:
    - value: 1
      label: benzine
      disabled: true
    - value: 2
      label: diesel
      checked: true
      disabled: true
- name: input-radio-inline
  context:
    __title: inline
    __explanation:
    - Een keuze selectie tussen <code>ja</code> en <code>nee</code> vraagt om een inline variant. Dit is te bereiken door <code>.dso-inline</code> op <code>.dso-radios</code> te zetten.
    id: input-radio-inline
    label: Group radios - Inline - Invalid
    helpText: ""
    required: true
    inline: true
    state: invalid
    errorText: Maak een keuze.
    options:
    - value: 1
      label: ja
    - value: 2
      label: nee
- name: input-radio-inline-info
  context:
    __title: infobutton
    __explanation:
    - Een radio fieldset kan op twee plekken een info button krijgen. Naast de de vraag en per optie. Als een toelichting is opengeklapt moet er <code>.dso-open</code> op de toelichting button geplaatst worden.
    id: input-radio-inline-info
    label: Group radios - Inline
    required: true
    helpText: Antwoord hier met "Ja" of "Nee"
    options:
    - value: 1
      label: ja
      checked: true
      infoOpen: true
      infoButtonLabel: Toelichting bij antwoord
      infoText: |
        <h4>Toelichting bij antwoord: "ja"</h4>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
          Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
          Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
        </p>
    - value: 2
      label: nee
      infoButtonLabel: Toelichting bij antwoord
      infoText: |
        Closed
    infoOpen: true
    infoButtonLabel: Toelichting bij vraag
    infoText: |
      <h4>Toelichting bij vraag: "Gaat het om de bouw van één of meer woningen?" </h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
        Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
        Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
      </p>
    infoTextDeprecated: |
      <h4>Toelichting bij vraag: "Gaat het om de bouw van één of meer woningen?" - BINNENKORT DEPRECATED</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
        Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
        Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
      </p>
