status: ready
collated: true
context:
  __title: static
  label: Kleur van object
  value: Rood
  __explanation:
  - Een static input kan informatie tonen die van belang is in een formulier zonder dat er een keuze gemaakt dient te worden.
variants:
- name: static-editbutton
  context:
    __title: Static edit button
    infoOpen: false
    infoButtonLabel: Toelichting bij vraag
    value: |
      <p>Het zichtbare spectrum is het gedeelte van het elektromagnetisch spectrum dat gezien kan worden door het menselijk oog.</p><p>Elektromagnetische straling binnen dit spectrum wordt ook wel zichtbaar licht genoemd.</p>
    edit: true
    __explanation: false
- name: static-infobutton
  context:
    __title: Static infobutton
    infoOpen: false
    infoButtonLabel: Toelichting bij vraag
    infoText: |
      Closed
    __explanation: false
- name: static-infobutton-open
  context:
    __title: Static infobutton uitgeklapt
    infoOpen: true
    infoButtonLabel: Toelichting bij vraag
    infoText: |
      <h4>Toelichting bij vraag: "Kleur van object"</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
        Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
        Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
      </p>
    infoTextDeprecated: |
      <h4>Toelichting bij vraag: "Kleur van object" [DEPRECATED]</h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam non metus dolor. Pellentesque velit arcu, pellentesque at lacus sit amet, porta semper est.
        Praesent mollis lorem lorem, non varius nisl lacinia et. Integer quis sollicitudin arcu. Nullam lacinia non ipsum sit amet varius.
        Praesent consequat ligula id tortor elementum pretium. Integer ligula justo, volutpat sed tellus eu, faucibus fringilla lectus.
      </p>
    __explanation: false
