status: wip
collated: true
context:
  type: button
  modifier: default
variants:
  - name: default
    label: Default button
    context:
      label: Vorige
  - name: disabled
    label: Disabled button
    context:
      label: Vorige
      type: submit
      modifier: default
      disabled: true
  - name: primary
    label: Primary submit button
    context:
      label: Volgende
      type: submit
      modifier: primary
  - name: primary-disabled
    label: Primary disabled button
    context:
      label: Volgende
      type: submit
      modifier: primary
      disabled: true
  - name: button-link
    label: Button-link
    context:
      label: Button-link
      type: submit
      modifier: link
      icon: fa fa-angle-right
  - name: button-link
    label: Button-link
    context:
      label: Button-link
      type: submit
      modifier: link
      icon: fa fa-angle-right
      disabled: true
