notes: |
  Het filterblok is een compositie die gebruik maakt van component `.dso-highlight-box` verrijkt met de `.dso-context-wrapper` modifier, om de [Alle opties]-knop naast het label te plaatsen.

  In deze compositie wordt voorts een `.dso-label-group` geplaatst voor de gekozen opties (filters).
status: ready
context:
  __title: default
  labels:
  - label: Geldend
    status: bright
  - label: Regels
    status: bright
  - label: Tuin
    status: bright
  - label: Woongebied
    status: bright
  - label: Geluidzone
    status: bright
  - label: 'Thema: milieu algemeen'
    status: bright
