notes: |
  Met een filterblok ...
status: ready
context:
  __title: default
  labels:
  - label: Geldend
    status: bright
  - label: Regels
    status: bright
  - label: Tuin
    status: bright
  - label: Woongebied
    status: bright
  - label: Geluidzone
    status: bright
  - label: 'Thema: milieu algemeen'
    status: bright
