notes: |
  Toont een progress-bar. Let op het gebruik van correcte waardes voor `aria-valuenow` (de huidige waarde van de progressbar), `aria-valuemin` (de minimale waarde) en `aria-valuemax` (de maximale waarde).
status: ready
collated: true
context:
  statustext: Een moment geduld a.u.b.
