meta:
  webComponent: dso-progress-bar
status: ready
collated: true
context:
  __title: Standaard
  progress: 60
  progressLabel: "Genereren export: Nog ongeveer 4 minuten."
  value:
    min: 0
    max: 100
variants:
  - name: non-default-values
    context:
      __title: Niet-standaard waarden
      progress: 3
      progressLabel: "Bestanden comprimeren: 12 stuks."
      value:
        min: 0
        max: 12
