status: ready
context:
  __title: default
  title: H1 Paginatitel
variants:
  - name: with-substitel
    context:
      __title: Met subtitel
      subtitle: H2 Subtitel
  - name: with-subtitel-and-steps
    context:
      __title: Met subtitel en stappen
      subtitle: H2 Subtitel
      step: Stap x van x
