status: ready
context:
  __title: default
  title: H1 Paginatitel
variants:
  - name: with-subtitle
    context:
      __title: Met subtitel
      subtitle: H2 Subtitel
  - name: with-subtitle-and-steps
    context:
      __title: Met subtitel en stappen
      subtitle: H2 Subtitel
      step: Stap x van x
  - name: just-subtitle
    context:
      __title: Alleen subtitel
      title:
      subtitle: H2 Subtitel
  - name: just-subtitle-and-steps
    context:
      __title: Alleen subtitel en stappen
      title:
      subtitle: H2 Subtitel
      step: Stap x van x
