notes: |
  Plaatst een afbeelding. Gebaseerd op de Bootstrap "Images" component

  Afbeeldingen kunnen responsive-friendly worden gemaakt via het toevoegen van de .img-responsive class.
  Deze voegt 'max-width 100%', 'height auto' en 'display block' toe aan de afbeelding, zodat hij netjes met zijn parent meeschaalt.

  Om afbeeldingen, die gebruik maken van .img-responsive, te centreren - gebruik .center-block in plaats van .text-center
status: ready
collated: true
context:
  __title: default
  source: /dummy/images/avatar.png
  alt: Alternatieve tekst
variants:
  - name: Responsive
    context:
      __title: responsive
      modifier: img-responsive
  - name: Rounded
    context:
      __title: rounded
      modifier: img-rounded
  - name: Circle
    context:
      __title: circle
      modifier: img-circle
  - name: Thumbnail
    context:
      __title: thumbnail
      modifier: img-thumbnail
